### ISSUE TITLE
Inconsistent keyboard focus in dark /high contrast mode 

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#10237]
**What**
"as I carry on tabbing though there is no keyboard focus shown at all now in this top section that underline and border has disappeared."

**Where**
Throughout the site. Demonstrated in high contrast in Windows.

**TODO**

- [ ] Check if this is also an issue on Macs
- [ ] Make sure focus is shown on Windows in high contrast / dark mode 
- [ ] Make sure focus is shown on Macs in high contrast / dark mode if necessary

**Background**

From the Hassell Inclusion accessibility audit August 2023.

Dovetail: https://proficient-wallaby-dpwd.dovetailapp.com/insights/Dark-mode-high-contrast-mode-handles-keyboard-focus-inconsistently-jfyRsfZBLyScODrsIdBeP

Miro board: https://miro.com/app/board/uXjVMjsL5YE=/

**Comment by pollecuttn** [comment]
![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/1446072/59ecaf0b-1166-48b9-b787-0ce265617456)


There is nothing to show that any of the top sections are selected in high contrast on Windows.
