### ISSUE TITLE
Design MVP for events in search

### ISSUE THREAD

**Issue by j-jaworski** [wellcomecollection/wellcomecollection.org#10569]
- [x] Competitor analysis
- [x] Review old designs
- [x] Wireframe MVP user journey
- [x] UI designs for MVP
- [x] Explore futher iterations

**Comment by j-jaworski** [comment]
Linked to #10547 

**Project page on Notion**
https://www.notion.so/wellcometrust/Events-in-search-MVP-60a16906279a4ee696892a6eb0cad5f9?pvs=4

**Design on Figma**
https://www.figma.com/file/e6Nng9zRjZITtYAZHpF1dB/Events-%26-Exhibitions-in-Search?type=design&node-id=0%3A1&mode=design&t=ynBQMDEUlTBfKETU-1
