### ISSUE TITLE
Cookies consent designs

### ISSUE THREAD

**Issue by j-jaworski** [wellcomecollection/wellcomecollection.org#10597]
Replace existing cookie banner with a legally compliant pop-up and a preferences centre on WC.org to allow users to manage their cookies

## Background

- Wellcome Collection's cookie policy is not compliant as it does not allow users to accept cookies or manage their cookie consent preferences
- If a user wants to view our cookie policy and information on our site cookies then they are taken to a page on another website ([wellcome.org](http://wellcome.org/), with its own cookie banner) with no intuitive way to navigate back to WC
- All cookies for both sites are listed together so users cannot differentiate between the relevant ones
- No link on [WC.org](http://wc.org/) (eg in footer) to find preferences centre to update cookie preferences

**More details on Notion roadmap**
https://www.notion.so/wellcometrust/Cookie-consent-dedae08913da484aadf75c2e4b004ecf?pvs=4

**Scope work**
- [x] Review designs with wellcome.org designers
- [x] Check-in with wellcome.org and WC team (scheduled 23 Jan)
- [x] Kick-off meeting (scheduled 24th Jan)
----

**Design work**

- [x] Competitor analysis
- [x] Review designs on wellcome.org
- [x] Wireframe user journey
- [x] UI designs first draft
- [ ] Review designs first draft
- [ ] Finalise designs

**Comment by LFBaily** [comment]
if it's helpful I just came across this design and ur for cookies which was undertaken in 2021 but didn't then seem to go anywhere: https://github.com/wellcomecollection/wellcomecollection.org/issues/7275 - perhaps some helpful insights

**Comment by rcantin-w** [comment]
This is the Civic UK documentation and the pages I think will be most useful to you:

https://www.civicuk.com/cookie-control/documentation/branding
https://www.civicuk.com/cookie-control/documentation/appearance
https://www.civicuk.com/cookie-control/documentation/text

Let me know if you have any question or want to test some scenarios.

**Comment by j-jaworski** [comment]
Designs completed on Figma, will go through in design reviews tomorrow.

This design file includes
- Wireframes for journey and content
- Ideal state for UI that would work across both wellcome.org and wellcomecollection.org
- Prototype to illustrate the animation and user journey

[Figma designs link](https://www.figma.com/file/5bZXZ08XyU8IOgyjd9ZsGe/Cookies-update?type=design&node-id=2%3A27&mode=design&t=XCYtEtxpMifP5JWV-1)
[Prototype link ](https://www.figma.com/proto/5bZXZ08XyU8IOgyjd9ZsGe/Cookies-update?page-id=2%3A27&type=design&node-id=2312-2634&viewport=-9008%2C-1515%2C0.5&t=OF2Vu1merfAKJ8Hc-1&scaling=min-zoom&starting-point-node-id=2312%3A2634&mode=design)

**Comment by j-jaworski** [comment]
Still to do:
- [ ] - Upate UI for toggles 
- [ ] - Footer designs to include Cookies preference link

**Comment by rcantin-w** [comment]
Footer point might be for #10707
