### ISSUE TITLE
Born-digital MVP designs

### ISSUE THREAD

**Issue by j-jaworski** [wellcomecollection/wellcomecollection.org#10600]
MVP of opening up access to born-digital files to allow users to download files from the Works pages

## Background

Wellcome Collection is increasingly collecting materials for the collections that are considered ‘born digital’: this includes things like the contents of hard drives, emails, audio, video, digital images, including some born digital material that is in legacy/unsupported file formats. Often this material comes as part of a mixed collection (physical and digital) from a person or organisation.

The born digital items are catalogued in Calm along with the rest of the acquired collection.

Born digital material is subject to the same access conditions as the rest of the physical collection. You can read more about these access conditions in the Access Policy ([[§12, page 7-8](https://wellcomecollection.cdn.prismic.io/wellcomecollection/d4817da5-c71a-4151-81c4-83e39ad4f5b3_Wellcome+Collection_Access+Policy_Aug+2020.pdf)](https://wellcomecollection.cdn.prismic.io/wellcomecollection/d4817da5-c71a-4151-81c4-83e39ad4f5b3_Wellcome+Collection_Access+Policy_Aug+2020.pdf)). In short, material can be:

- Open
- Open with advisory
- Restricted
- By appointment
- Temporarily unavailable
- Closed

**More details on Notion Roadmap**
https://www.notion.so/wellcometrust/Born-digital-files-available-to-download-4b6a311ef48a4ad1bc7428b66d0d3768?pvs=4

**Design work**

- [x] MVP designs UI including copy that frames the user experience and explains the limitations of born-digital files "You're on your own"

**Comment by aray-wellcome** [comment]
Hello! I've only just gotten to look at this ticket and I wanted to point something out in case it's helpful. 

> > Born digital material is subject to the same access conditions as the rest of the physical collection. You can read more about these access conditions in the Access Policy ([[§12, page 7-8](https://wellcomecollection.cdn.prismic.io/wellcomecollection/d4817da5-c71a-4151-81c4-83e39ad4f5b3_Wellcome+Collection_Access+Policy_Aug+2020.pdf)](https://wellcomecollection.cdn.prismic.io/wellcomecollection/d4817da5-c71a-4151-81c4-83e39ad4f5b3_Wellcome+Collection_Access+Policy_Aug+2020.pdf)). In short, material can be:
> 
> Open
> Open with advisory
> Restricted
> By appointment
> Temporarily unavailable
> Closed

This bit isn't quite accurate. The Archivematica METS (and Goobi METS for that matter) and the IIIF manifest will only have the following access conditions that are applied by a human at point of ingest:

1. Open
2. Open with advisory
3. Restricted
4. Closed

(And the secret option of Clinical which I don't think we're using anymore but we do have digitized items with this access condition). 

The access conditions By Appointment and Temporarily Unavailable are not actually access conditions and are not put into the METS or IIIF manifest. 

Instead, they're physical availability statuses, not applicable to digitized or born digital items. As far as I can tell this is a status that would be applied to physical items from the Requesting API via a field in Sierra or maybe CALM. In the case of born-digital items, I suppose a availability condition of By Appointment would mean they have to come into the library and look at it on a dedicated terminal.

**Comment by j-jaworski** [comment]
After reviewing with the team and getting a slightly better idea of what we might want to display 

- [ ] Iterate and separate out archive tree and file directory
- [ ] Maybe run a co-design session
- [ ] Talk to an archivist
- [ ] Talk to Ashely more

**Comment by j-jaworski** [comment]
Iteration of designs based off feeback in review

https://www.figma.com/file/mCoPMnDgbrbf33qhogphGp/Born-Digital?type=design&node-id=2083%3A931&mode=dev&t=WK4HZpNRwmhkifuo-1


[Born digital works page.pdf](https://github.com/wellcomecollection/wellcomecollection.org/files/14331111/Born.digital.works.page.pdf)

**Comment by aray-wellcome** [comment]
> Iteration of designs based off feeback in review
> 
> https://www.figma.com/file/mCoPMnDgbrbf33qhogphGp/Born-Digital?type=design&node-id=2083%3A931&mode=dev&t=WK4HZpNRwmhkifuo-1
> 
> [Born digital works page.pdf](https://github.com/wellcomecollection/wellcomecollection.org/files/14331111/Born.digital.works.page.pdf)

This is definitely looking more like I was picturing it with the files listed in the main body of the works page. This is a great example to use because of the complexity of the hierarchy and I think the collapsible display works for it well. 

The metadata (access, kind, size) it a good start for me. I'd be interested to hear what other metadata the collections team would also like to see here specifically. Hopefully not a ton because there's not that much room to work with.

**Comment by j-jaworski** [comment]
@aray-wellcome thanks for your comments, yeah feels like it is much closer to something that would work for users, the feedback on the previous iteration of the design was super useful.

In terms of metadata, I think it would be good to get an idea of what the collections team want, but we should try and stay user-centred and try as best we can to avoid a long list of data that doesn't enhance the users' experience of the page. The meta data should be meaningful to users. One thing I considered but left off was the `Date created` as I thought this could actually confuse users as it is different to the `Publication/Creation` meta data on the works page

**Comment by aray-wellcome** [comment]
@j-jaworski Date created! I forgot about that one. I think it provides important context to the born-digital files (some of them are from the early 90s for example) but I can see how it might be confusing to users. Maybe there's better wording for it...

**Comment by j-jaworski** [comment]
Is the `Date created` the same for all the items in a born digital manifest? If so, I suggest we add it below under the **About this work** heading.

**Comment by aray-wellcome** [comment]
No, the date created for the files would all be different I imagine. Just like anything on your hard drive

**Comment by j-jaworski** [comment]
Ah I was looking at the created property on here 
https://iiif-stage.wellcomecollection.org/dash/Asset/6/PPKIN_B_2_5_3---Roberta_Cowell---www.transgenderzone.com---features---sex_change.htm

**Comment by aray-wellcome** [comment]
Ah that created property is when the IIIF manifest was created so that shouldn't be displayed.

**Comment by LaurenFBaily** [comment]
Reviewed with archivists on Friday 8th. Only questions raised were:
1. Should we limit downloads per person? - this is a broader question so not specific to this piece of work, not a blocker
2. Should we offer feature for user to download the whole folder? - @aray-wellcome confirmed we are unable to currently offer this so won't be part of MVP (also could be huge)
3. For files within a born-digital work, should the file names themselves be restricted? - @aray-wellcome thinks this shouldn't be the case

Thinking about next steps or how we move this into Done:
- Do we need designs for what happens on smaller screens?
- Do we need session with devs to interrogate designs and create tasks for build?
- What happens when a file name is very long (assuming that is a possibility)?

**Comment by aray-wellcome** [comment]
Just to clarify on point 3: Toni has said she thinks collections still stands by not wanting the IIIF manifests created for restricted born-digital items  in order to restrict the file name. So we would not be showing any file names for restricted items (which would be impossible without a IIIF manifest to read from anyway) on a public works page.

Though as we wanted to show restricted born-digital items on a staff-logged in works page we would need to create the IIIF manifest but put it behind the login for access. This is work we were going to look into with Digirati but hadn't yet and we don't have a solid idea on it just yet. 

And on the point of `What happens when a file name is very long (assuming that is a possibility)?` we actually have one item that has a file name so long that we can't create a IIIF manifest for it right now :/ I believe it's over 220 characters.

**Comment by LaurenFBaily** [comment]
Thank you Ashley, was hoping you would chime in there as my notes on that weren't quite up to scratch.

**Comment by j-jaworski** [comment]
Designs are done! I think... 

[Link to creative in Figma](https://www.figma.com/file/mCoPMnDgbrbf33qhogphGp/Born-Digital-MVP-designs?type=design&node-id=2238%3A233&mode=design&t=K38Dt4Ybjy2Mow0C-1)

This file includes:
- Current born digital works pages for reference
- Designs for desktop, tablet and mobile 
- Annotated designs
- Interatavtive prototype to illustrate the folders opening and closing
- List of new components and assets 

I will go through this in the next FE catch up or design review ✌
