### ISSUE TITLE
Refactor code for transforming iiif manifest/canvas and for rendering canvas items

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#10606]
## Background

When we [transform a iiif manifest](https://github.com/wellcomecollection/wellcomecollection.org/blob/aaa23633e5d31b8d6a9829a43de14b10a2182ffc/content/webapp/services/iiif/transformers/manifest.ts#L29) we pull out the data for canvas items that contain [audio](https://github.com/wellcomecollection/wellcomecollection.org/blob/aaa23633e5d31b8d6a9829a43de14b10a2182ffc/content/webapp/services/iiif/transformers/manifest.ts#L31), [video](https://github.com/wellcomecollection/wellcomecollection.org/blob/aaa23633e5d31b8d6a9829a43de14b10a2182ffc/content/webapp/services/iiif/transformers/manifest.ts#L34), and [pdfs](https://github.com/wellcomecollection/wellcomecollection.org/blob/aaa23633e5d31b8d6a9829a43de14b10a2182ffc/content/webapp/services/iiif/transformers/manifest.ts#L36) and [return them as properties on the TransformedManifest](https://github.com/wellcomecollection/wellcomecollection.org/blob/aaa23633e5d31b8d6a9829a43de14b10a2182ffc/content/webapp/services/iiif/transformers/manifest.ts#L69) separately from the [rest of the canvas items](https://github.com/wellcomecollection/wellcomecollection.org/blob/aaa23633e5d31b8d6a9829a43de14b10a2182ffc/content/webapp/services/iiif/transformers/manifest.ts#L86)

This kind of made sense, as 1) up to now our iiif manifests have only contained items of a single type and 2) we have dealt with these types of things separately. For example, for audio and video files we render players on the works page rather than pointing them to the item page. For pdfs we use the browsers pdf renderer on the item page rather than our [IIIFViewer component](https://github.com/wellcomecollection/wellcomecollection.org/blob/aaa23633e5d31b8d6a9829a43de14b10a2182ffc/content/webapp/components/IIIFViewer/IIIFViewer.tsx#L36). At present the IIIFViewer is incapable of rendering these types of things.

With the introduction of born digital items [into the iiif manifests](https://github.com/wellcomecollection/docs/blob/main/rfcs/046-born-digital-iiif/README.md) things have changed. We now have [manifests that can contain a mix of file types](https://iiif-stage.wellcomecollection.org/presentation/PPKIN/B/2/5/3) and we have to be able to [render these different things together](https://github.com/wellcomecollection/wellcomecollection.org/issues/10568).

In #10605, we grab the data needed to display all the items, regardless of what they are, and add it to the TransformedCanvas. It isn't quite that straightforward, as at the moment we want the data to create download links, not to render the item itself and for Born Digital items the download data is different to the display data

## What should we do next
We should use the display data now on the canvases to render items, both the audio/video players on works page and the images in the IIIFViewer, because:

- we would simplify the TransformedManifest by removing the pdf, audio and video properties (everything we need would be on the canvases property)
- we would remove code duplication introduced in #10605, that overlaps with code in the getAudio, getVideo and getPdf functions
- the way of grabbing the display data introduced in #10605 is more robust than the equivalents in getAudio, getVideo, getPdf and getImageService functions.
- would go along way in the direction of making [this](https://github.com/wellcomecollection/wellcomecollection.org/issues/10494) possible if we decide to resurrect the issue.

## How should we do it
- [x] get all the data we need for each canvas type ('Image', 'Audio', 'Video' etc) onto the transformed canvas. #10605 did a lot of this already, but we'd need to make sure we're grabbing everything the getAudio, getVideo, getPdf functions currently do, e.g transcripts
- [x] render the works page ~and items pages making use of this data~ - only if we decide the viewer should be able to render everything
- [x] remove the pdf, audio and video properties from the transformedManifest, once they aren't used, and all the code for generating/testing them.

N.B. canvases currently only make the image service for an item available.  Placeholder images for born digital items don't have one, which is why they are aren't being rendered in the IIIFViewer.
