### ISSUE TITLE
Look at Civic UK Pro version from UX / UI design perspective

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#10673]
## Definition of ready
- [x] We have a Pro licence 

## What
Follows up #10657: Explore various aspects of the Civic UK configuration https://www.civicuk.com/cookie-control/documentation with @j-jaworski and play around with what's possible.

## Definition of Done
- [x] We agree on whether or not we are happy with Civic UK's flexibility in UX/UI.
- [ ] If we agree we're happy, we can suggest a final configuration.

**Comment by rcantin-w** [comment]
For the DoD checkbox;
>  If we agree we're happy, we can suggest a final configuration.

The final config will come as part of #10597 , in the meantime the basic configuration with more relevant copy has been made available on prod.
