### ISSUE TITLE
Design landing page & cross-promotion of visual stories

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#10690]
https://www.notion.so/wellcometrust/Finding-Visual-stories-f0bfedcbe62c4b79b49d37e931acf4f9

**Comment by kasiabbb** [comment]
**Current sprint + Firebreak**: 18-29 Mar (Planning)

- [ ]  KB to finish research and project plan (by 19.03)
    - [ ]  Finalise the research plan
    - [x]  Finalise the project management plan
    - [ ]  Divide work into Github tickets
    - [ ]  Decide on the incentive (reach out to Katie)
- [ ]  KB to draft research materials (by 20.03)
    - [ ]  Draft participant emails / reach-out copy for Slack and Trustnet
    - [ ]  Draft screen survey
    - [ ]  Draft test script
- [ ]  KB to create two Figma protytypes (per research plan) (by 25.03)

- [ ]  KB to co-create  success criteria with the Product team - suggestion from Sara to the right (by 27.03):
    - [x]  KB to book the session (booked for 27.03)
    - [ ]  run the session

> 
- [ ]  KB to r[[each out](https://www.notion.so/Visual-Stories-access-reach-out-copy-a28973ee99a7440690da01e89ad3723a?pvs=21)](https://www.notion.so/Visual-Stories-access-reach-out-copy-a28973ee99a7440690da01e89ad3723a?pvs=21) to participants (by 22.03)
- [ ]  KB create a [[participant userbase](https://www.notion.so/52adafc7535941e588ab36494669d8ec?pvs=21)](https://www.notion.so/52adafc7535941e588ab36494669d8ec?pvs=21) (by 28.03)
    - [ ]  KB to schedule 10-12 usability testing sessions (by 28.03)
    - [ ]  KB to randomise participants into group A/B (by 28.03)

**Sprint 0**: 2 - 9 Apr (user testing)

- [ ]  KB to facilitate sessions: 3, 4, 5, 8 April

**Sprint 1**: 10.04 - 23.04 (Sessions and analysis)

- [ ]  KB to facilitate sessions: 9, 10, 11 (if necessary)
- [ ]  KB to collate and analyse data based on pre-agreed success criteria (by 12.04)
- [ ]  KB to send Thank you email to participants (12/04)
- [ ]  KB to create a report with findings (23.04)

**Sprint 2: 24.04 - 03.05 (shortened because of my holiday)**

- [ ]  KB to create an updated Figma design based on findings (by 02.05)
- [ ]  Playback session (by 03.05)
