### ISSUE TITLE
Build WC cookies page

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#10706]
### What?

Create new page for information about cookies, including an up to date list of categorised cookies.
Content has been updated and approved by legal here: https://wellcomecloud.sharepoint.com/:w:/s/Legal/EUVgdmoNbilPsuhmS0u3-ugB1G7yZfoi-0FZwR4qsdr9HQ?e=2u4voQ

### Why?

Updating our consent management and as part of that separating out the wc.org specific cookies.

### Background

Part of cookie consent work: https://www.notion.so/wellcometrust/Cookie-consent-dedae08913da484aadf75c2e4b004ecf?pvs=4

### Done when

- [x] New page live with updated content
- [x] 'Cookie policy' linked from the Manage cookies panel

**Comment by LaurenFBaily** [comment]
Need to agree how we display some of the marketing cookies, eg. can we consolidate as suggested here: https://www.notion.so/wellcometrust/Cookies-across-products-d3d801413bc84673bbaa100a8db097a2?pvs=4#26205f5f4af54625a30e4e058a87ef32

**Comment by rcantin-w** [comment]
Which marketing cookies do we have?

**Comment by LaurenFBaily** [comment]
Pixel tracking has been approved for Wellcome, although I read the paper on it and only wellcome.org is mentioned. I will follow up again with Elizabeth.

That second comment is only relevant if there are marketing cookies.

**Comment by rcantin-w** [comment]
To clarify, this is a NEW page, that replaces the "Privacy & Terms" link in footer that we currently have. It is renamed "Privacy, terms and cookies", is that right?

**Comment by LaurenFBaily** [comment]
Yes it should be a new page. And yes we will want to call out cookies specifically in the copy although can't remember if the wording has been agreed anywhere, let me check...

**Comment by rcantin-w** [comment]
If it's hard-coded, what would you like the URL to be @LaurenFBaily ?
And as we discussed this morning, this is now solely a cookies page.

**Comment by rcantin-w** [comment]
Rewrite:
> You can withdraw your consent to the use of Cookies or manage any other Cookie preferences by changing your Cookie settings. This page can also be accessed by clicking on "Cookie settings" in the footer of our websites. You can then adjust the radio buttons to "on" or "off " and save. You may need to refresh your page for your settings to take effect.

**Comment by LaurenFBaily** [comment]
Edited title and description to reflect change from Privacy and Terms page to just a new Cookies Policy page.

**Comment by rcantin-w** [comment]
Blocked as waiting for confirmation on content

**Comment by LaurenFBaily** [comment]
Descriptions need to be signed off by data protection lead and coordinated across products

**Comment by rcantin-w** [comment]
Blocked by #10717 for the cookie tables listing bit, but the copy itself also needs re-reading and re-writing (see https://wellcomecollection.org/cookie-policy behind `cookiesWork` toggle for notes in red), so maybe this ticket can be moved to In progress/Next?

**Comment by LaurenFBaily** [comment]
- [ ] (7) Cookies meta description:

This policy contains information on cookies used on the Wellcome Collection website and how to manage your cookie preferences. 

- [ ] (1) Change text to: You can withdraw your consent to the use of cookies or manage any other cookie preferences by changing your cookie settings. This page can also be accessed by clicking on "Manage cookies" in the footer of our websites. You can then adjust the slider buttons to "on" or "off " and save. You may need to refresh your page for your settings to take effect.

- [ ] (2 & 4) Remove 'Disclaimer' subheading and all information under it

- [ ] (3) I think for now just remove the sentence: 'This includes social networks, such as Facebook, Instagram, LinkedIn and Research Gate.'

- [ ] change ‘Cookies’ to ‘cookies’ in all instances (remove capitalisation)

- [ ] Update date for policy last updated to 17th April 2024

- [ ] Google Analytics section should be updated to:

We use analytics cookies on our websites. These collect information related to the number of visitors to the website, where visitors have come to the website from, and the pages they visited. We use the information to compile reports and to help us improve the website. We use the following analytics cookies on our websites: 

- [ ] (5) Change first two paragraphs to:

This Cookie Policy relates to your use of the Wellcome Collection websites (https://wellcomecollection.org/).

When you choose to accept or reject cookies on one of our websites, your choices are valid for that website only. If you click through to another website, whether operated by us (including [Wellcome Trust](https://wellcome.org/) or [Wellcome Funding](https://funding.wellcome.org/)) or a third party you will need to make separate choices in relation to the cookies that you would like to accept or reject on that other website.

**Comment by LaurenFBaily** [comment]
Reviewed, looks great thanks.

**Comment by rcantin-w** [comment]
Changes have been deployed to production; only thing left is to fill the table but that's a different ticket #10717  so closing this one
