### ISSUE TITLE
Remodel exhibition resources in Prismic

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#10819]
## Background
The [Exhibition guides ](https://wellcomecollection.org/guides/exhibitions) present various problems for both users and content editors that largely result from the fact that they conflate two distinct things, i.e. 1) audio guides and 2) gallery text and wall captions.

The audio guides are aimed at the general public visitor, and are additional (optional) content to the exhibition itself. They are described as a ‘highlight tour’ which has been primarily designed as an audio experience but is also available as a BSL video (with transcripts available)

The text and wall captions are to aid visitors who cannot easily read the labels in the exhibition.

## Solution

Split the exhibition guide type into two distinct custom types in Prismic.

- [x] Create a audio-guide/highlight-tour (name tbc) custom type in Prismic which includes only those fields necessary to render the audio/video components, including transcripts (I think that is everything minus the tombstone, caption, standalone title, context)

- [x] Create a custom content type ‘Exhibition text’ which only allows editors to add the content displayed on this page (https://wellcomecollection.org/guides/exhibitions/ZSaiohAAACMAlJbK/captions-and-transcripts) minus the transcripts

We should use multiLineText fields instead of the singleLineText fields currently being used, to allow editors to copy and paste content more easily. See ['pain points' document](https://docs.google.com/document/d/1eYSZJPmUpeYXJ2lgy1mCDsZY3fZOdOyYRnlNS7bLZi4/edit)

- [x] Archive the exhibition-guide content type
