### ISSUE TITLE
Update the Exhibition Guides index page

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#10822]
Following #10821

Update the[ Exhibition Guides index page](https://wellcomecollection.org/guides/exhibitions/Zdcs4BEAACMA6abC) to more clearly signpost the different resources as well as the navigation between resources.

**Comment by LaurenFBaily** [comment]
FYI we have an upcoming instance of an exhibition (Kola Nuts, a temporary "display" in gallery 3) which will have a "captions" page but no audio/bsl highlight tour content. If it doesn't already, the index page will need to be able to just display the captions card. Hoping the work you're doing @gestchild to separate these out will make this straightforward.

**Comment by LaurenFBaily** [comment]
Dependent on https://github.com/wellcomecollection/wellcomecollection.org/issues/10914

**Comment by LaurenFBaily** [comment]
Designs finalised now, so:

- [ ] Add subtitles and text
- [ ] Update card style
- [ ] Update title to '[Exhibition title] digital guides'

Design link to be added.
![Image](https://github.com/user-attachments/assets/872b5dd2-9920-4883-9c64-1202d15134d3)

**Comment by kasiabbb** [comment]
Access on [Figma](https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=361-382&t=1YlSKBWbJdNsKy8F-1) , Key Screens-Mobile space

**Comment by rcantin-w** [comment]
Changes on prod behind toggle fyi @kasiabbb
