### ISSUE TITLE
Upgrade Node versions

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10846]
We need to look at upgrading our Node versions as most of our project is running on Node 16 [and that is deprecated](https://nodejs.org/en/blog/announcements/nodejs16-eol). (More info about other versions [in their repo](https://github.com/nodejs/release#release-schedule))

Here's what we're currently on for all the sub-repos, linked with their upgrade ticket:

- [x] Common/Content/Identity (Node 16) - #10923 
- [x] Cardigan (Node 16) - #10922 
- [x] **Dash (Node 18)** - #10926 
- [x] Toggles (Node 16) - #10925 
- [x] **Pa11y (Node 18)** - #10924 
- [x] Prismic-model (Node 16) - #10928 
- [x] Updown (Node 16) - #10927 

---
- [x] cache/edge_lambdas (12 and 16) * #10929 

So some are on 18 already, but as 20 is the current LTS we're thinking we could trial that first. 18 reaches EOL at the end of April 2025, so would be nice to not have to think about it for a while (20 gives us an extra year).

It could (and should) be done in multiple steps, as many as there are sub-repos above, except for the first one which should happen at the same time. There is also the *special case of `cache/edge_lambdas`, which is partly running on Node 12, which means we have to think about _how_ to move it over more carefully (there is no staging environment, therefore no way to test it).

This ticket could serve as an epic equivalent for this piece of work.

- [x] Another task is to make sure we "un-pin" node versions in our workflows: [see comment below](https://github.com/wellcomecollection/wellcomecollection.org/issues/10846#issuecomment-2186665417)
- [x] Edit the root `.nvmrc` and remove unnecessary ones.
- [x] Write up recommendations for future Node upgrades protocols: https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/DPDDj27NI2F2kPukWrC1/language-tool-specific-notes/nodejs-updates

**Comment by rcantin-w** [comment]
I've just noticed this as a TODO in our github workflow files:

```
 # TODO: Remove this line when we can safely upgrade all our packages
      # to versions that support Node 16.
      # See https://github.com/wellcomecollection/wellcomecollection.org/pull/9324
      - uses: actions/setup-node@v4
        with:
          node-version: 16
```

Coming from [this PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/9324)

So I'll add it as a thing to do in this ticket's description.

**Comment by rcantin-w** [comment]
David published this NodeJS upgrade process in Gitbook: https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/DPDDj27NI2F2kPukWrC1/language-tool-specific-notes/nodejs-updates

A good test will be for the next person that upgrades to use it and see if anything is missing/not necessary/anything.

@pollecuttn @LaurenFBaily, as reviewing our Node versions should be a recurring task (we haven't decided have we? Possibly twice a year?), an idea could be to have a link to this document in future Node upgrade tickets/quarterly plannings.

**Comment by rcantin-w** [comment]
> Edit the root .nvmrc and remove unnecessary ones.

Will get done once https://github.com/wellcomecollection/wellcomecollection.org/issues/10929 is deployed.

**Comment by rcantin-w** [comment]
Closing as all done and deployed to prod
