### ISSUE TITLE
Create a "More Visual Stories” section near the page footer in every Visual Story page.

### ISSUE THREAD

**Issue by kasiabbb** [wellcomecollection/wellcomecollection.org#10884]
## User story

As a neurodivergent user accessing a visual story
I want to see what other visual stories there are available
So that I can be confident planning a visit to exhibitions at Wellcome Collections

## What?

Create a section for discovering more visual stories in every Visual Story page. 

It will be placed at the bottom of the page, above the footer, and visible from the in-page nav as "More visual stories"

It should only show:
- the generic visual story (https://wellcomecollection.org/visual-stories/ZU0PSRIAACkATr2l)
- Visual Stories to active exhibitions, so as of now, Jason's adventure (https://wellcomecollection.org/exhibitions/ZZP8BxAAALeD00jo/visual-stories)

Access the designs here:
Figma dev mode link (I think this is a new Figma feature, pasting in in case helpful): https://www.figma.com/design/GNL0nN8xkshpBY75LSzMoZ/Visual-Stories-landing-page?m=dev&node-id=789%3A101&t=y80gkfKNB53RMPvI-1

Figma regular link: https://www.figma.com/design/GNL0nN8xkshpBY75LSzMoZ/Visual-Stories-landing-page?node-id=789%3A101&t=y80gkfKNB53RMPvI-1

Figma screenshots:

![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/161052675/45911261-b474-42e1-87db-19939f0ac5df)

## Done when
- [ ] "More Visual Stories" added to the in-page navigation on current Visual Story pages
- [ ] "More Visual Stories" element added at the bottom of each current Visual Story page
- [ ] only current exhibition Visual Stories are linked through this element
- [ ]  Documentation updated
