### ISSUE TITLE
Create a text highlight element for the Visual Story page body contents

### ISSUE THREAD

**Issue by kasiabbb** [wellcomecollection/wellcomecollection.org#10885]
## User Story
As a neurodivergent user accessing a visual story
I want to see what other visual stories there are available
So that I can be confident planning a visit to exhibitions at Wellcome Collections

## What?
Add the yellow highlight element to every Visual Story link inside another Visual Story

![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/161052675/1a2c4b9b-0ffc-4c66-b08b-e6200622baa7)

## Why? 
Currently links buried inside the guide, not very visible. 

## Done when
- [x] Links to other Visual Stories highlighted in all current Visual Story documents
- [x] Documentation updated in https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/451yLOIRTl5YiAJ88yIL/custom-slices#info-block (#10959)
- [x] Communicate with editors on the slice being added and make it clear what it's to be used for.
- [x] Remove button from slice as per [Slack conversation](https://wellcome.slack.com/archives/CUA669WHH/p1717682159491849).

**Comment by rcantin-w** [comment]
We discussed it with Lauren and Kasia and we're happy doing this, but we'll need to make it very clear what the slice is to be used for. Historically, InfoBlock has been used for an array of reason and we'd like to ensure it doesn't get used for any reason. So;

- Adding a description to the slice if we can for editors
- @LaurenFBaily to update the Slice description here https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/451yLOIRTl5YiAJ88yIL/custom-slices#info-block
- And of course, communicate with editors once it's made available with a clear guidance on how it's to be used.

**Comment by rcantin-w** [comment]
Waiting on possible name change?

**Comment by rcantin-w** [comment]
Blocked by #10959

**Comment by rcantin-w** [comment]
https://wellcomecollection.org/exhibitions/ZZP8BxAAALeD00jo/visual-stories change made here. The `InfoBlock` is now available on visual stories and only offers title and content, no more buttons.

The three places we found that used the button have been replaced by a link.

Just noticed the styles are slightly different, with the list being indented on the mockup but not in our current `InfoBlock` styles. I'm not super sure why, it uses `.body-text` which overrides the padding on the left, so it does seem intentional. Is that something we'd like me to look into?

![Image](https://github.com/wellcomecollection/wellcomecollection.org/assets/110461050/88e1c8d4-0247-41e6-be03-8a3b342d55fc)

**Comment by rcantin-w** [comment]
[Changes communicated to Editorial in Slack](https://wellcome.slack.com/archives/C3N7J05TK/p1719408577800309).

Name of the component will not be changed as per [this ticket's conclusion](https://github.com/wellcomecollection/wellcomecollection.org/issues/10959).

So closing this ticket - we can create a new one if we want to address the list styles; it's a different piece of work anyway.
