### ISSUE TITLE
Design updated UX flow for Exhibition Guides

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#10914]
### What
Design new UX flow for users accessing digital exhibition guides during their visit

### Why
Resolve known problems with user experience of exhibition guides https://wellcomecollection.org/guides/exhibitions/Zdcs4BEAACMA6abC

### Background
See https://www.notion.so/wellcometrust/Improve-usability-of-exhibition-guides-e846b1cd33b049c384fcab7ab4b3b05e

### Done when
- [x] UX flow created and annotated in Figma
- [x] feasibility confirmed with the dev team
- [ ] signed off with stakeholders (Georgia)

**Comment by kasiabbb** [comment]
UX has been now handed over to the team for development. https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=361-382&t=bfeRnWHjSXhkTxVO-1
