### ISSUE TITLE
Upgrade Node: pa11y

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10924]
Parent ticket with all information: https://github.com/wellcomecollection/wellcomecollection.org/issues/10846

- [ ] Node has been updated to the highest possible version
- [ ] `.nvmrc` file has been added/updated
- [ ] All tests are running

**Comment by rcantin-w** [comment]
Deployed successfully
