### ISSUE TITLE
Upgrade Node: Cardigan

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10922]
Parent ticket with all information: #10846

- [x] Node has been updated to the highest possible version
- [x] `.nvmrc` file has been added
- [x] All tests are running

**Comment by davidpmccormick** [comment]
Completed in #10992
