### ISSUE TITLE
Upgrade Node: Main website

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#10923]
Parent ticket with all information: https://github.com/wellcomecollection/wellcomecollection.org/issues/10846

This is for the Common, Identity and Content sub-repos.

- [x] Node has been updated to the highest possible version
- [x] `.nvmrc` file has been added
- [x] All tests are running

**Comment by davidpmccormick** [comment]
Work in #11006
