### ISSUE TITLE
Transcripts

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11038]
Add transcripts on audio and video stop pages.

- [x] Add new field to Prismic for BSL video transcript called 'Video subtitles'
- [x] Display transcript under audio stop pages
- [x] Display subtitles on BSL video stop pages

**Comment by kasiabbb** [comment]
Design resources:

https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=1393-7182&t=RuXOgPioiApqd7op-1

spec tab, tour stop spec
