### ISSUE TITLE
Create new highlight tour stop cards (audio & video)

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11043]
### What
Create new highlight tour stop cards for audio stops and video stops

[See designs here](https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=1434-16939&t=RuXOgPioiApqd7op-1).

### Why
Moving from having all audio/video clips displayed on one page to having a page per stop so we need new cards to display on the highlight tour pages. 

### Done when
- [x] Audio highlight tour card (with and without image) 
- [x] BSL video highlight tour card (with and without image) 
- [x] Add to Cardigan?

**Comment by kasiabbb** [comment]
Design resources: 

https://www.figma.com/design/YY8hrWmKYhLm8ZQeYaKiLm/Exhibition-guides?node-id=1434-16939&t=RuXOgPioiApqd7op-1

Spec Tab: 
- Digital Augio Guide Stop Card
- Digital BSL Guide Stop Card

**Comment by rcantin-w** [comment]
Cardigan is a good shout, as it builds on PRs, we could have Kasia QA it before merging, iterate on her feedback and then merging what we consider to be the final version.
