### ISSUE TITLE
Set up and test tracking for Hard Graft guides

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11142]
Ensure usage/engagement of new exhibition guides can be tracked.

- [x] Add campaign parameters to QR code urls and provide to Exhibitions team
- [x] [Update formulas in URLinator spreadsheet](https://wellcomecloud.sharepoint.com/:x:/r/sites/wc2/DE/Editorial/Documents/[URLinatedURLs.xlsx](https://wellcomecloud.sharepoint.com/:x:/r/sites/wc2/DE/Editorial/Documents/URLinatedURLs.xlsx?d=w4a6db307d92346f1964f201b4b84e64f&csf=1&web=1&e=yMr952)?d=w4a6db307d92346f1964f201b4b84e64f&csf=1&web=1&e=yMr952) for future guides
- [x] HotJar tracking on exhibition guides
- [x] Update Gitbook guidance on setting up urls for tracking

**Comment by LaurenFBaily** [comment]
Urls for the QR codes here with GA campaign tracking:
https://wellcomecollection.org/guides/exhibitions/ZsdFlRIAACIAqKGB?usingQRCode=true&stopNumber=1&utm_source=Gallery1&utm_medium=QRCode&utm_id=HardGraftGuides&utm_content=Stop1

https://wellcomecollection.org/guides/exhibitions/ZsdFlRIAACIAqKGB?usingQRCode=true&stopNumber=2&utm_source=Gallery1&utm_medium=QRCode&utm_id=HardGraftGuides&utm_content=Stop2

https://wellcomecollection.org/guides/exhibitions/ZsdFlRIAACIAqKGB?usingQRCode=true&stopNumber=3&utm_source=Gallery1&utm_medium=QRCode&utm_id=HardGraftGuides&utm_content=Stop3

https://wellcomecollection.org/guides/exhibitions/ZsdFlRIAACIAqKGB?usingQRCode=true&stopNumber=4&utm_source=Gallery1&utm_medium=QRCode&utm_id=HardGraftGuides&utm_content=Stop4

https://wellcomecollection.org/guides/exhibitions/ZsdFlRIAACIAqKGB?usingQRCode=true&stopNumber=5&utm_source=Gallery1&utm_medium=QRCode&utm_id=HardGraftGuides&utm_content=Stop5

https://wellcomecollection.org/guides/exhibitions/ZsdFlRIAACIAqKGB?usingQRCode=true&stopNumber=6&utm_source=Gallery1&utm_medium=QRCode&utm_id=HardGraftGuides&utm_content=Stop6

https://wellcomecollection.org/guides/exhibitions/ZsdFlRIAACIAqKGB?usingQRCode=true&stopNumber=7&utm_source=Gallery1&utm_medium=QRCode&utm_id=HardGraftGuides&utm_content=Stop7

https://wellcomecollection.org/guides/exhibitions/ZsdFlRIAACIAqKGB?usingQRCode=true&stopNumber=8&utm_source=Gallery1&utm_medium=QRCode&utm_id=HardGraftGuides&utm_content=Stop8

https://wellcomecollection.org/guides/exhibitions/ZsdFlRIAACIAqKGB?usingQRCode=true&stopNumber=9&utm_source=Gallery1&utm_medium=QRCode&utm_id=HardGraftGuides&utm_content=Stop9

https://wellcomecollection.org/guides/exhibitions/ZsdFlRIAACIAqKGB?usingQRCode=true&stopNumber=10&utm_source=Gallery1&utm_medium=QRCode&utm_id=HardGraftGuides&utm_content=Stop10

https://wellcomecollection.org/guides/exhibitions/ZsdFlRIAACIAqKGB?usingQRCode=true&stopNumber=11&utm_source=Gallery1&utm_medium=QRCode&utm_id=HardGraftGuides&utm_content=Stop11

https://wellcomecollection.org/guides/exhibitions/ZsdFlRIAACIAqKGB?usingQRCode=true&stopNumber=12&utm_source=Gallery1&utm_medium=QRCode&utm_id=HardGraftGuides&utm_content=Stop12

**Comment by LaurenFBaily** [comment]
Need to check on Monday but think I need to switch campaign ID with campaign name for utm tracking to get the existing report to work eg. https://wellcomecollection.org/guides/exhibitions/ZsdFlRIAACIAqKGB?usingQRCode=true&stopNumber=12&utm_source=Gallery1&utm_medium=QRCode&utm_campaign=HardGraftGuides&utm_content=Stop12

**Comment by LaurenFBaily** [comment]
Wahoo - utm campaign tracking working
![Image](https://github.com/user-attachments/assets/e1c2d8ee-eaec-4741-9f60-b111d830a4cd)

Now just need to update Gitbook and the spreadsheets so future exhibition guides can be set up without our help.

**Comment by LaurenFBaily** [comment]
All done!
