### ISSUE TITLE
Exhibition page accessibility section update

### ISSUE THREAD

**Issue by LaurenFBaily** [wellcomecollection/wellcomecollection.org#11173]
### To do

- [ ] Remove the 'Digital access content' section from exhibition page 
- [ ] Make content changes to yellow box 
- [ ] Add new 'Access resources' section including accordion
- [ ] Re-order exhibition page components (gallery, yellow box, related events, access resources, related stories)
- [ ] Rename 'In this exhibition' to 'Exhibition events'

1. See design link:
2. See word doc for Access resources content: https://wellcomecloud-my.sharepoint.com/:w:/r/personal/l_baily_wellcome_ac_uk/Documents/Exhibition%20access%20copy%5B31%5D.docx?d=w83af6d26e2594c6bbcb8c01ebc646ff3&csf=1&web=1&e=FWiunK

**Comment by rcantin-w** [comment]
Designs aren't in the ticket I think?
