### ISSUE TITLE
Build and run the Hotjar survey

### ISSUE THREAD

**Issue by kasiabbb** [wellcomecollection/wellcomecollection.org#11276]
User story
As a user reading an article
I want to be recommended other stories along the same or similar subjects
So that I can continue to discover and read different perspectives and experiences of health

UX brief
research brief: https://docs.google.com/document/d/1xsec3I3QM0WGRhaip_3Lfgt-y-YQicLXHVyepHsyjTk/edit
Miro exploration board: https://miro.com/app/board/uXjVLS7YqfQ=/?share_link_id=117786911242
More information on Notion (project brief, meeting notes, etc.): https://www.notion.so/wellcometrust/Onward-journeys-from-Stories-28a038bcc6cf4643854ea9007090a6d3?pvs=4

Definition of done
- [ ] use the agreed research brief to build a Hotjar survey building understanding of Stories readers
- [ ] Decide on the duration of the survey (X)
- [ ] Run the survey for (X)
