### ISSUE TITLE
Id-based URL tidy up

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#11292]
Tidy up that I think belong in a separate piece of work just before we remove the ID-based fetching support.
- [x] ~~Remove `looksLikePrismicId` helper from codebase?~~ Update comments above helper to explain UID/ID.
- [x] Change URLs in tests to be final URLs (`/pages/WuxrKCIAAP9h3hmw` -> `pages/media-office` -> `about-us/media-office`, might as well wait until we're done).
- [x] Amend URLs in all markdown files (e.g. https://github.com/wellcomecollection/wellcomecollection.org/blob/main/docs/library-membership.md)
- [x] Ensure "Edit in Prismic" link in API toolbar still works
- [x] Ensure Previews in Prismic still work

**Comment by rcantin-w** [comment]
The Prismic previews seem to have been working as normal, so I'll consider that checked. If anything comes up, we can address it then.

**Comment by rcantin-w** [comment]
in prod
