### ISSUE TITLE
Add a HotJar survey to all Stories pages

### ISSUE THREAD

**Issue by kasiabbb** [wellcomecollection/wellcomecollection.org#11331]
User story
As a user reading an article
I want to be recommended other stories along the same or similar subjects
So that I can continue to discover and read different perspectives and experiences of health

UX brief
research brief: https://docs.google.com/document/d/1xsec3I3QM0WGRhaip_3Lfgt-y-YQicLXHVyepHsyjTk/edit
Miro exploration board: https://miro.com/app/board/uXjVLS7YqfQ=/?share_link_id=117786911242
More information on Notion (project brief, meeting notes, etc.): https://www.notion.so/wellcometrust/Onward-journeys-from-Stories-28a038bcc6cf4643854ea9007090a6d3?pvs=4

## What?

We need to add a Hotjar survey to all Story articles. [more information TDB] 

## Why?

This is to collect information on how users currently use Stories and to gage their interest in being exposed to more content on Wellcome Colleciton. 

## Background

This is part of the Stories onward journeys epic, which is currently in research/design phase by @kasiabbb

## Done when

- [x] code added that allows us to display the HotJar survey on all Story pages on wellcomecollection.com
- [x] Kasia to create the survey on Hotjar 
- [x] reviewed with Lauren and Kasia
- [x] survey questions, 
    - [x] design, 
    - [x] duration - 1 week
    - [x] target responses : 
267 - 90% confidence level in our results
100 - minimum (low confidence: use results as inspiration/ guidance rather than a source of truth) 
- [x] survey running live on all the Story pages

**Comment by gestchild** [comment]
Code to add hotjar to stories page done in #11325
