### ISSUE TITLE
Create recruitment brief for user research agency

### ISSUE THREAD

**Issue by florabowden** [wellcomecollection/wellcomecollection.org#11362]
Using personas, write recruitment brief to address needs for discovery research for browse.

Done when:

- [x] Recruitment criteria for all personas is defined
- [x] Quote signed off
- [x] Recruitment brief signed off
