### ISSUE TITLE
Explore UR recruitment options with existing WC users

### ISSUE THREAD

**Issue by florabowden** [wellcomecollection/wellcomecollection.org#11361]
Done when:

- [x] Explore possibility of in-person research with users in the library, archive, exhibitions: Look into recruitment to user panel through concept page pop-up research (to participate in later stages of research).
- [x] Look into Wellcome Collection user panel - discuss policy on using existing panel to determine if it can be used for Browse Discovery, or if new participants should be recruited.
- [x] Explore adding banner to collections website to invite participants.
