### ISSUE TITLE
Build recommended stories component

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#11425]
Build a horizontally scrollable component containing minimal Stories cards. ~~These stories will be fetched from a hard-coded list of `uid`s.~~ (**dev update: I've hard-coded in the information**)

This will be built behind a toggle so it can be turned off by any dev should we want to pause the testing.

A GA event will be created for this.

This should display:
- ~~On all stories EXCEPT webcomics and image galleries~~ After discussing with Lauren we decided it'll only show on formats: `undefined`, `article` and `long-read`.
- After X paragraphs (@kasiabbb can you confirm how many?) **dev update: have gone for 5**
- Nice to have: Only if it has enough paragraphs to slide it into **dev update: this should work based on the implemented logic**
- Nice to have: Only between two paragraphs **dev update: won't do**

### Definition of Done
- [x] Integrated as per designs (@kasiabbb to confirm designs and link them to this ticket)
- [x] GA event added and working (@LaurenFBaily to assist with this)
- [x] List of articles final (Editorial to confirm which one - @LaurenFBaily to communicate?)

**Comment by kasiabbb** [comment]
The banner should display after 5 paragraphs where possible. 

It should adhere to the designs [here](https://www.figma.com/design/6XYRHJjrRGVveTenps4iWZ/Deepen-engagement-with-stories?node-id=131-1182&m=dev&t=K3AEGvXzWtWwwwOV-1)

![Image](https://github.com/user-attachments/assets/3e893f61-b5ae-4f6f-bfb5-78a9eaa03e1c)

Story recommendations below - they should display in a random order:

Finding Audrey Amiss 
https://wellcomecollection.org/series/finding-audrey-amiss

Medieval mobility aids
https://wellcomecollection.org/stories/medieval-mobility-aids

My hair is not
https://wellcomecollection.org/stories/-my-hair-is-not--
 
Brief history of tattoos
https://wellcomecollection.org/stories/a-brief-history-of-tattoos
 
Yes I Am
https://wellcomecollection.org/stories/yes-i-am--voices-of-autistic-women-from-minoritised-communities
 
The breastmilk market
https://wellcomecollection.org/series/the-breastmilk-market

**Comment by rcantin-w** [comment]
Popular stories is now available in prod on all stories (of formats: undefined, article or long-read), under the "Recommended stories" toggle! 

As discussed, the logic of where it shows up is not perfect (see PR and ticket for more details), but we'll build it more seriously when/if we build it seriously.

The toggle can be made public by any dev when you want if you'd like to release it during the week, there's just the question of the analytics not having anything special on it yet - so I'll assign this ticket over to @LaurenFBaily for that part!

![Image](https://github.com/user-attachments/assets/fd7d5177-1e82-4094-8c70-277c5889141c)

**Comment by LaurenFBaily** [comment]
Analytics in place (thanks @davidpmccormick!) just needed a little bit of troubleshooting. I've updated our list of events in [Gitbook here](https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/MM8zK9GZyFCpy8kvd5Km/analytics-and-reporting/analytics-event-tracking) although that page is likely out of date and will need to be audited by incoming analyst.
