### ISSUE TITLE
Create design propositions for the "Related Stories" onward journey

### ISSUE THREAD

**Issue by kasiabbb** [wellcomecollection/wellcomecollection.org#11433]
Create design propositions from the ideation workshop results for the "Related Stories" at the bottom of the article. Make sure the designs are aligned with the prioiritised design hypotheses.

Checklist:

- [x] design idea props
- [x]  signed off with Lauren
- [x] consulted feasibility with David 
- [x] sign off a list of Stories for test placement + the "related" story for each
- [x] Build and deploy component (#11439)

Flags:

- [x] Do we want to make any amends to the wording of section headings? @LaurenFBaily 

Designs [(figma link)](https://www.figma.com/design/6XYRHJjrRGVveTenps4iWZ/Deepen-engagement-with-stories?node-id=312-2139&t=EWT3EZbsSlH438Fx-1) "Final design -related stories" section

![Image](https://github.com/user-attachments/assets/64f741dd-7967-4e77-831a-f71ba3f19ed8)

**Comment by kasiabbb** [comment]
Added design files, assigned @davidpmccormick in case you want to pick it up, or feel free to assign someone else. Also assigned @LaurenFBaily for consultation on the section titles (at the moment "Your next read" and "Do not miss")

**Comment by rcantin-w** [comment]
I've added a ticket for "Build and deploy component" and have added the link next to the checkbox so if you want to consider it done for _this_ ticket, it could be closed once @LaurenFBaily confirms the copy!

**Comment by LaurenFBaily** [comment]
I'm considering this done as Editorial are clear on the brief now and are putting together the list. They will be able to add these directly through Prismic.
