### ISSUE TITLE
Buttoning up our Cardigan

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#3196]
# Who it's for
US!

Cardigan needs some love. This issue contains ideas for things to document and refine.

# Aim
The aim is to develop the design system as a useful tool for people working on or contributing to wellcomecollection.org: designers, developers, content editors, brand folks, etc.

## High-level Documentation
- Vision and mission of WC
- Product personality and creative attributes (provocative, playful, purposeful and eclectic);
- **Dev + Design principles** including accessibility, performance strategy, product design principles
- **Global elements**: Visual elements (wobbly line, dividers); Grid; Templates; Icons; Colour Palette; Typography; Logo 
- **Content design resources**: links to relevant guidance (style guide, tone of voice guidelines, image approach, etc)

- Components grouped by 'family', e.g. Navigation, Buttons, Images etc (Storybook)

## TODO

- [ ] Scope out what we need to make this useful to a designer @GarethOrmerod @DominiqueMarshall 

- [x] update storybook to 5.3 https://medium.com/storybookjs/storybook-5-3-83e114e8797c
- [ ] Grouping components #4754 
- [ ] Audit for missing components
- [ ] Audit for missing documentation
- [ ] Discuss process/workflow

- [ ] Improving documentation for each component
- document rationale for page header styles
- status indicator states (what we have and colour association)
- [x] Create a README template
- [ ] Include details in every README
- [ ] Link to user research wherever possible
- [ ] Add any event tracking per component
- [ ] Update browser support document
- [ ] Review naming conventions and recommend new names
- [ ] Show how groups of components fit in grid
- [ ] Reskin Cardigan so it’s on brand
- [ ] Make our own homepage with intro
