### ISSUE TITLE
Accessibility testing of recent collections discovery work: search, work page, digital item preview, full viewer

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4202]
### Aims/Purpose
We need to get our recent collections discovery work in front of researchers with access needs, specifically neurodiverse and visual impairments.

### Tasks

- [x] Talk to Orla and Selene about recruitment process
- [ ] Check with devs re build of thing to be tested and set deadline
- [ ] Write script
- [ ] Review script with Product Manager
- [ ] Pilot (optional)
- [ ] Think about extras we could add in to the test
- [ ] Update room booking
- [ ] Send Bluejeans links to transcribers
- [ ] Book testing room
- [ ] Email Reception with participants' names
- [ ] Check Bluejeans set up is working
- [ ] Book viewing room
- [ ] Email team with viewing room invite
- [ ] Print consent forms/script
- [ ] Add link to script on Sharepoint to this issue

**Comment by hthair** [comment]
In discussion with Orla about how to diversify our recruitment for feedback sessions. Regrouping later this week to discuss how we can act on this for next quarter.
