### ISSUE TITLE
Event series with frequent events over several months: design challenge for S&M Live Performances

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4404]
# Background

Smoke & Mirrors Live Performances are happening from April-September in the gallery.
These performances are by different performers, with multiple sessions over multiple days.
It is not feasible to treat this as an event with schedule, as the timeframe is too long, and to make the schedule usable would require Content Editors to delete past performances (which is not what we want). 

I propose turning [this]([url](https://wellcomecollection.org/events/XK7jkxIAAMAbQC9L)) 

![screenshot-wellcomecollection org-2019 04 17-12-02-06](https://user-images.githubusercontent.com/1446139/56283103-a9ec9e80-6108-11e9-89c6-34d9237635e4.png)

into an Event Series, so that we can:
- Make contributor/performers more visible
- Retain the past events
- Minimise ongoing efforts of content team in having to pare back a really long schedule after performances

# Problems to be solved
One of the major problems is that this approach is photography-greedy. We would need:
- a featured image for the Event Series
- An image for each event, e.g. Performance by Dr Gustav Mahler
- A headshot for the contributor/performer (optional)

## EXAMPLE 1
This screenshot is an example of why this might be a problem if we have one image to represent everything (if we have events lined up for several months, using the same image, it would be a wall of repeating images:

![SM - In Gallery promo - screenshot-preview wellcomecollection org-2019 04 16-10-33-26](https://user-images.githubusercontent.com/1446139/56283347-60508380-6109-11e9-9e68-0c54e3ef8af1.png)

## EXAMPLE 2

We *could* develop an approach where it is possible to not display a promo image in the card, as shown here: 
![SM - In Gallery no promo - screenshot-preview wellcomecollection org-2019 04 16-10-33-26](https://user-images.githubusercontent.com/1446139/56283423-9db51100-6109-11e9-8d22-13dcab877e9d.png)

We would then be able to use the same image on each event, with the caveat that this would be a bit weird where we list upcoming events (`home`, `/whats-on` and `/events`)

But this approach would allow photography to be done independently of the perfomers, with a focus on more audience-le group shots, rather than performer-focussed shots. 

**We could do this now, but Alice has pointed out that she is unable to publish an event without a promo image, and there's no way to not display an image on the card.**

# TODO 
- [ ] Discuss photography approach with Ben and @dannybirchall 
- [ ] Decide whether we want to try to use a no-image card + repeat featured image across all events
- [ ] Experience team to think about how we might test putting 'Event Series' card on listing pages, rather than individual events (similar to Daily Tours card)
- [ ] Redirect `/events/XK7jkxIAAMAbQC9L` to new Event Series page (once created)

**Comment by dannybirchall** [comment]
To connect the event series to the exhibition page, we will be need to be able to add the event series content type as well as events to the 'in this exhibition' section of the exhibition page; 

Currently it's locked to events content type only , as shown in this screenshot

![image](https://user-images.githubusercontent.com/3763790/56284615-e3bfa400-610c-11e9-8412-bc256fd4e1ad.png)

**Comment by Heesoomoon** [comment]
What if we display the contributor card below each event to 'make contributor/performers more visible'? This model would fit nicely for 'Why music' festival in future.

![56283423-9db51100-6109-11e9-8d22-13dcab877e9d](https://user-images.githubusercontent.com/29206031/56302199-31e69e80-6131-11e9-8de0-5e4e22d73462.png)
