### ISSUE TITLE
Library content plan

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4414]
After #4395 (Discovery & Guidance) research is finished, we'll need to scope out new and adapted content requirements.

# Todo
- [x] Content inventory on wellcomelibrary.org - @jennpb 
- [x] Turn Project Giles recommendations into user questions/user stories; split between practical visiting info and collections discovery info - Lalita @jennpb 
- [x] Agree new content to create and existing content to test
- [x] Prioritise new content ideas based on user value + short/long-term feasibility
- [x] Map new content to updated wellcomecollection.org sitemap 
- [x] Plan for redirecting where possible

# Documents
One Website Content Audit: https://wellcomecloud.sharepoint.com/:x:/s/wcdigitalexperience/EVeHngngpGVCl16B3AzCzcsB4GnN86AuMBVH3YDxpcEhXA?e=qpQ7lZ

Sitemap: https://octopus.do/izz1roh504

Research content framework, aligning user needs / user questions / ideas : https://docs.google.com/document/d/1eMqfe_ILIPx4I61JjcdTVDga32AqZokrmtBEyJLEESc/edit?usp=sharing

**Comment by jennpb** [comment]
New content to create falls into these categories:

**Functional (Q4)**
- Visiting, facilities, services
- Joining the library 

**About the collections** 
- History: Legacy, clarify relationship to Science Museum, evolution of our collections
- Now: Describing as it relates to how library works, how to navigate our collection, in reference to current collection development policy; overview 

**Researcher engagement**
- Partnerships with institutions, academic groups
- Opportunities: internships, ECR placements, Collaborative Doctoral Awards 

**Research guides** 
- Getting started with (e.g.) Family History
- Topic-based (replacing user need that archives subject guides used to serve)
- How-to (use an archive, etc) 

**“Collections”**  
- Hero/featured
- Dynamic (browse by genre, subject, author, organisation, worktype; alpha ideas)
- Digital

Next steps: Content team to manage prioritisation and planning for all content. Reference documents produced are in main body of this issue.

**Comment by jennpb** [comment]
Part of https://github.com/wellcomecollection/platform/issues/4646
