### ISSUE TITLE
Increase number of Venue Hire enquiries from website

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4528]
## Who it's for
Meeting planners using the Venue Hire pages

## Problem to be solved
Despite traffic to all of the Venue Hire pages being UP compared to the previous 6 months, this isn’t translating into increased bookings. The total number of events are down, and total number of enquiries are down as well. Given the ambitions for the next FY, we need to look at making some changes that might contribute to increased conversion to bookings + income. 

## Hypotheses
- Lack of a clear, obvious call-to-action is offputting
- People missing the contact information

## Goal
Increase number of enquiries from the website.

## Ideas
- Make contact details more obvious (try #4355)
- Test a contact form as a way of gathering lightweight prospect information, so the Event Sales team can reach out more effectively (NB Dan pointed out that Meeting Planners are often working on the go and may not always want to trigger the device's email client, so a form they can fill out separately may encourage more contact).

## TODO
- [ ]  Get baseline data from Dan C (number of email/phone enquiries in last 3 months and number of email/phone enquiries leading to a booking)
- [x] Set up Google Form as a test
- [ ] Agree placement on Venue Hire page with @dannybirchall and @Heesoomoon 
- [ ] Button CTA
