### ISSUE TITLE
Online requesting: design ideal user flow

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4727]
## Who it's for
Us

## Problem to be solved
Need to map out the ideal flows for different access levels
- Existing, current library members
- New members
- Expired members

So that users can:
- Order materials from closed stores from wc.org

Current wl.org flow: https://www.notion.so/wellcometrust/4582-Online-Request-46f03c1e3b8143e99e3e17d2449697ce

## TODO
- [ ] Draw out user stories from existing research
- [ ] Team to work out ideal flows, given pain points we're trying to resolve
- [ ] Produce user flow diagrams
