### ISSUE TITLE
Introduce scrolling when rendering digitised content

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4856]
Part of #4848 

**Aims:**

1. Make it easier to move between pages
2. Optimise for touchscreen behaviour

We discussed following PDF viewer mental model: 
- scrolling images vertically
- exposing a bit of the next image to encourage scrolling (and possibly eliminate the need for nav arrows)
- Introduce scrolling thumbnail sidebar in detail view
- Scrollbar to help zoom through

##TODO/Questions to resolve:
- [ ] how/when to update url when scrolling main view, i.e. which page is THE page being viewed (which page will rotate, zoom, download apply to)
- [ ] when click thumbs, how does this update the main view? if image one is in main view and user clicks thumbnail 200, how do we ensure all 198 images in between aren't loaded?
- [ ] Test functionality across browsers/devices
- [ ] currently when paginating, the viewer manifest is called/loaded every time - need to investigate
- [ ] Styling see - #4885

# Implementation
## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations
<---Delete as appropriate--->

- Impact on URL design
- Cardigan documentation
