### ISSUE TITLE
Getting more user feedback via search relevance ranker

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4975]
# Problem to solve
We're not getting much explicit search relevance feedback from the lovely component we built. There are probably a few reasons for this. 

For now, our aim is to **get more staff use over a period of 4 weeks**

Then: Data team to review - is data useful to them? Are we getting more useful feedback this way?

If not, shut it off. 

## TODO
- [x] Tacey to review existing data 
- [x] More advocacy amongst staff - emails, website update presentation, jenn to tweet?
- [x] Data team to review once we have more data
~~Shut off if not working (or revisit component design later)~~
- [x] Put it behind a toggle so it's available for future ranking needs

**Comment by taceybadgerbrook** [comment]
Here is what has been happening with the relevanceRanker since it was deployed on 31/10/19:

![image](https://user-images.githubusercontent.com/32418070/72360684-3a7ffb80-36e8-11ea-98fa-bd884c664f43.png)

![image](https://user-images.githubusercontent.com/32418070/72360651-250ad180-36e8-11ea-91c0-a0e2312644be.png)

**Comment by taceybadgerbrook** [comment]
Since 31/10/19, there have been 654k events not involving toggles, so 552 is 0.08% of all activity

**Comment by taceybadgerbrook** [comment]
Certain users really engage.  
![image](https://user-images.githubusercontent.com/32418070/72361717-df4f0880-36e9-11ea-877a-29e86465685e.png)

But these the heaviest users aren't the ones who are rating the searches
![image](https://user-images.githubusercontent.com/32418070/72361915-2806c180-36ea-11ea-9322-b02d19dc9fbd.png)

**Comment by taceybadgerbrook** [comment]
I checked how many searches the top 10 most engaged users were doing and they range from 7 to over 200, so most of these people do know what a good search result looks like.

I think the issue with non-participation is that there's nothing in it for them.

**Comment by taceybadgerbrook** [comment]
Here's a link to the Kibana dashboard which runs from 1/1 (to show the effect of promoting this in Cat Chat on 10/1):

https://reporting.wellcomecollection.org/app/kibana#/visualize/edit/2e91f270-384f-11ea-98b6-0dff1a41ca28?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2020-01-01T00:00:00.000Z',to:now))&_a=(filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'0370c5c0-0182-11ea-a050-0352b7b3fbe3',key:network.keyword,negate:!f,params:(query:StaffCorporateDevices),type:phrase),query:(match:(network.keyword:(query:StaffCorporateDevices,type:phrase))))),linked:!t,query:(language:kuery,query:''),uiState:(),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!f,extended_bounds:(),field:timestamp,interval:auto,min_doc_count:1,scaleMetricValues:!f,useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(addLegend:!t,addTimeMarker:!f,addTooltip:!t,categoryAxes:!((id:CategoryAxis-1,labels:(filter:!t,show:!t,truncate:100),position:bottom,scale:(type:linear),show:!t,style:(),title:(),type:category)),dimensions:(x:!n,y:!((accessor:0,aggType:count,format:(id:number),params:()))),grid:(categoryLines:!f),labels:(show:!f),legendPosition:right,seriesParams:!((data:(id:'1',label:Count),drawLinesBetweenPoints:!t,lineWidth:2,mode:stacked,show:!t,showCircles:!t,type:histogram,valueAxis:ValueAxis-1)),thresholdLine:(color:%2334130C,show:!f,style:full,value:10,width:1),times:!(),type:histogram,valueAxes:!((id:ValueAxis-1,labels:(filter:!f,rotate:0,show:!t,truncate:100),name:LeftAxis-1,position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:Count),type:value))),title:'Search%20relevance%20staff%20participation',type:histogram))

**Comment by jennpb** [comment]
Sorry @taceybadgerbrook that link doesn't work for me. It takes me straight to the homepage.  Is there a click path I can follow?

**Comment by pollecuttn** [comment]
@taceybadgerbrook Can you add that graph of use you had this morning here, please?
