### ISSUE TITLE
Improve design of digitised content preview

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#4977]
# Problem to solve
Our initial design intent with the content preview was to give users a flavour of a work, so they'd have a better idea of what it's like. 

Our choices around implementation were to:
- Provide a selection of randomised images, with title page, cover and first page of the contents being persistent, and the other images random (which means we can sometimes get blank pages, or muddy/ugly cover images)
- Indicate a multivolume set by showing the title page of the first volume of a multi-volume set
- Show a single image where that's all we have.

We now no longer feel this is the best representation of a work.

Areas to consider:
- CTA to open full or partially digitised work
- User journey from image search scope to work page 
- Can we get 'wow' factor in ways other than showing a sprinkling of images?

![screenshot-wellcomecollection org-2020 03](https://user-images.githubusercontent.com/1446139/72004380-2d27c480-3243-11ea-9094-89aa5afedcd9.png)
![screenshot-wellcomecollection org-2020 04](https://user-images.githubusercontent.com/1446139/72004413-44ff4880-3243-11ea-8be2-817dd4d993a2.png)
![screenshot-wellcomecollection org-2020 01](https://user-images.githubusercontent.com/1446139/72003923-4e3be580-3242-11ea-8673-ad4131168019.png)
![screenshot-wellcomecollection org-2020 02](https://user-images.githubusercontent.com/1446139/72004041-7d525700-3242-11ea-9c6b-9f0588a321bb.png)

# TODO
- [ ] #4529 Improving CTA from content preview
- [ ] #4339 Identify featured image which will represent whole work
- [ ] Sketching 'toolbar' ideas to aid navigation from work page > overview > reading view
- [x] #5026 Change default view in viewer to reading view (not thumbnail grid)

# Implementation
## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations
<---Delete as appropriate--->

- Impact on URL design
- Cardigan documentation

**Comment by pollecuttn** [comment]
30 January 2020
- Continuing with designs for:
    - single image
    - multi-image (not a book)
    - multi-image (book)
    - multi-vol (book)
    - video
    - audio
- Each section on the page will have a header to help with page hierarchy
- Licence info: leave as is for now; in future could move into 'Download' drawer after e.g. a licence filter is available
- Mock-ups for things that are available in library

**Comment by pollecuttn** [comment]
Test A/B versions of digi content slice

**Comment by pollecuttn** [comment]
16 March 2020: decision to switch to toggle B

**Comment by taceybadgerbrook** [comment]
A/B testing was carried over for the period 4 - 15 March inclusive.  The null hypothesis was that users behave the same regardless of the viewing buttons served.  The test found the probability of obtaining 1,710 toggle A users clicking to view vs 6,859 toggle B's to be less than 0.0001.  This indicates strong evidence in favour of rejecting the null hypothesis.

Conclusion:  users appear to be more inclined to click to view with the new /works viewer buttons.

Here is a link to the PowerPoint slides with the analysis:https://wellcomecloud.sharepoint.com/:p:/r/sites/wcdigitalexperience/Shared%20Documents/Analytics/4977%20works%20viewer%20AB%20testing.pptx?d=w9d2311879d3f403c8d42fe78c223824c&csf=1&e=vT06uT

**Comment by gestchild** [comment]
Option B, went live for everyone (19/3/2020 - 11:20am)

We therefore no longer capture the following events in GA:
category: 'IIIFImagePreview',
action: 'follow link',
label: <workId>

'IIIFPresentationPreview',
action: 'follow link',
label: <workId>

The following 3 events are instead captured by the WorkDetails component:
category: 'WorkDetails',
action: 'follow image link',
label: <workId>

category: 'WorkDetails',
action: 'follow view link',
label: <workId>

category: 'WorkDetails',
action: 'follow overview link',
label: <workId>
