### ISSUE TITLE
Stakeholder Discovery: how we talk about our collections to users

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5007]
# What is it?

This is a piece of discovery research to help us align user goals with business needs. I want to know:
- How colleagues engage the public with our collections
- What's the language our colleagues use when they talk to the public about the collections
- What existing tools (handouts, web content, events) are in place to help users understand what we have and why it's interesting
- What departmental KPIs from LE&E and C&R should we be paying attention to?
- Are there any homegrown materials in use by LE&E and C&R to solve user problems?

**AIM: To draft a content strategy specifically for researcher-audiences that helps us achieve our strategic aims, and allows us to create an informed backlog of ideas to design and test with users.**

## TODO
- [x] Draft a set of research questions
- [x] Get Discovery Beyond Search cluster firmed up 
- [x] Gather printed materials
- [x] Set up meetings with team leaders
- [x] Attend relevant team meetings as observer to take notes
- [x] C&R Ops Forum - 12 Mar 2020
- [x] Consolidate ideas into a single doc to play back to stakeholders
- [ ] Prioritise feature/content based on user value + short/long-term feasibility

## Docs
[Stakeholder research questions](https://docs.google.com/document/d/1rhipJaV5K-tFeErwohTOGAa3yQDQfykLTTf0uBnSMww/edit?usp=sharing)

**Comment by jennpb** [comment]
Notes documented on Notion: https://www.notion.so/wellcometrust/Stakeholder-discovery-about-our-collections-d51285315ce0475797821331fedea16f
