### ISSUE TITLE
User Research processes and recruitment

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#5172]
# What is it and who's it for?
Wellcome researchers would like to formulate the most valuable remote research process

# User story
In order to participate in user research with Wellcome
As an interested volunteer
I need/want/expect to be able to self apply for research opportunities online

## Acceptance criteria
User research participants should be able to show their interest in Wellcome's research process

# Implementation 

In order to land on an implementable design for a recruitment platform, we should consider the following:
- [x] Compliance for airtable for collecting data [WIP @alicerichmond] 
- [x] AD&I consultation group (talk to Orla) #5208
- [x] Research privacy policy that references up to wellcome.ac.uk privacy #5212
- [x] Write content brief for design research group #5234
- [x] Setting up tools (Lookback, Dovetail)
- [x] Publish content page

## Measurement
- Number of research participants undertaking remote usability testing

**Comment by pollecuttn** [comment]
@alicerichmond Please:
1. Assign this to yourself
2. Add this to the Project 'Experience Planning Board' and move to the 'In progress' column

**Comment by alicerichmond** [comment]
Link to Miro with usability testing work flow, along with search user journey

https://miro.com/welcomeonboard/XSgZhTVfDjv8exClXEBfIvqPXM0QxsZihJFpdkLGVNYlZrBe1wRcqV1dbbdtBHeR

**Comment by alicerichmond** [comment]
- Confirmed with Aoife from the Trusts user research team that Wereby is a suitable research product for usability testing

- Calendly can be used for booking times with us for research sessions

- Still awaiting confirmation from compliance from Airtable, should be confirmed by the end of this week
