### ISSUE TITLE
Discovery: Archive collections

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5231]
Light-weight discovery phase to give context to our work on **Improving discovery and presentation of archives**

**Understanding the domain**
- [x] Book an 'Intro to Archives' session with colleagues
- [x] Desk research: Is there any other published research re: archives discovery or navigating file structures etc? 
- [x] Competitor/Sector review - https://www.notion.so/wellcometrust/Library-Collections_Archives-53a8faa7c0ea4987a965542c77e7cdc4
- [x] Intro to data in API with Data team

**Designing a good service**
- [x] Define goals
- [x] Define how we'll measure success
- [x] User research: Existing and New 
- [x] Write user stories
- [x] Preliminary sketches/wireframes on priority areas

## Documentation
**Kickoff deck** https://docs.google.com/presentation/d/13X5PeDBxh7tdDxA2pUk8yyp6EY84svY30PwXtm1PPWY/edit?usp=sharing

How Might We? https://whimsical.com/7V7SWgHnCVYHbZ9nqt3PKN

Competitive Review https://www.notion.so/wellcometrust/Library-Collections_Archives-53a8faa7c0ea4987a965542c77e7cdc4#47c29ec2352b451c89aabcd169074eb0

## Epics

**Navigating an archive**
https://github.com/wellcomecollection/wellcomecollection.org/issues/5281
Knowing position no matter where you've come from:
- search engine > archive collection
- search engine > item in archive collection
- catalogue search > archive collection or item in archive collection

Knowing what this page is 
Knowing where you've been

Identify part of collection + place within it

**Prioritised information about archive**
https://github.com/wellcomecollection/wellcomecollection.org/issues/5282
Answer the user question: what will I find here?
Adapting /works template to accommodate all archive catalogue information
https://alistapart.com/article/priority-guides-a-content-first-alternative-to-wireframes/

**Viewing the material with clear, easy-to-find CTAs**
https://github.com/wellcomecollection/wellcomecollection.org/issues/5283
Request
View online

**Key facts about archive**
https://github.com/wellcomecollection/wellcomecollection.org/issues/5284
Answer the user question: How long will it take me to get through it? 
Physical size
Number of things to be viewed
What can be viewed online? In library?

**Access conditions, inc T&Cs for digitised content**
https://github.com/wellcomecollection/wellcomecollection.org/issues/5285

**Browsing archive collections**
https://github.com/wellcomecollection/wellcomecollection.org/issues/5286
Aggregated list of archive collections available
Alpha sort
Date sort

**Understanding how to use/"read" an archive**
https://github.com/wellcomecollection/wellcomecollection.org/issues/5287
Contextual help info
