### ISSUE TITLE
Find images in context of their parent work

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5233]
# What is it and who's it for?
We're mapping standalone digital images to their 'parent' works. This means that manuscripts, books, archives  that have had 1+ images photographed from them (but not cover-to-cover) will now have a set of selected images from the work. 

We need to display these images in context of the work page, and show what they're part of in search results.

It's for **Collections researchers**

## User story
In order to understand the context for an image
As a researcher
I need additional information about where it's come from, when it was made, etc.

# Initiatives
- [ ] Understand data coming from API
- [ ] Sketch out User journey from search > work > image
- [ ] Sketch out User journey from image search > related images > image
- [ ] Show related images on work page

## Acceptance criteria TBC

# Implementation 

## Testing and tracking
- Have you talked to Tacey?
- Test plan
- Will you need to set up additional tracking?
- What is the expected life span for tracking?

## Measurement
- Related KPIs (e.g. breadth of collection accessed, reading time, etc.)

## Other considerations 
<---Delete as appropriate--->
- Impact on URL design
- Cardigan documentation
