### ISSUE TITLE
Make full catalogue search available to public

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5289]
# What is it and who's it for?

Releasing whole catalogue search from behind the toggle so the works can be discovered

- For us - so we get a better idea of what people are to selecting from search results; also so we can be clearer to users what is being searched 

- For users - It's frustrating to only be able to search for some content that's digitised; and potentially confusing when they can't find evidence of what they need

# What would we need to do?
We haven't made the whole Sierra catalogue fully available to users yet because we were waiting to implement the online requesting functionality so users could request it directly from wellcomecollection.org, rather than moving across to wellcomelibrary.org.

Given the delays in implementing online requesting due to building closure, we need to look at getting the full Sierra catalogue searchable, to help recalibrate search behaviour and allow the Data team to assess search queries in context of the whole, rather than just the digitised stuff

We discussed the implications for removing the toggle in April 2020.

To address potential harmful user confusion, we established that we'd want to look at the following pieces of work before making the full catalogue available.

**MUST DO - Q4 2020**

1. Clear visibility of what's available online and what's available in the physical library
https://github.com/wellcomecollection/wellcomecollection.org/issues/4269
https://github.com/wellcomecollection/platform/issues/4724
- Need this data from the API
- Need to indicate on search result card whether item is online/in library
- Add online/in library filters

2. Address Collections landing page https://github.com/wellcomecollection/wellcomecollection.org/issues/5454
- Rewrite content on Collections landing page so it better reflects what's available

3. Pass users through to Wellcome Library website to request materials (when requesting service on) OR indicate that requesting not currently available (when requesting service is off)

**SHOULD DO**
5. Subscription database and journal links should be available through the API

6. Agree ways of capturing qualitative feedback - user satisfaction, did they find what they were looking for?

7. Test pagination ideas to give more control to users

8. Helpful message to reframe search query at page 400 of results

**Questions**

- Investigate whether others have login problems passing from wc to wl
- Find out whether we should be excluding Standing Orders
- Investigate whether ES limitations are self-imposed or whether we have control?

Notes from Whimsical April 2020
![Full catalogue@2x (1)](https://user-images.githubusercontent.com/1446139/81827777-03ecad00-9531-11ea-8671-df9c55021bb8.png)

**Comment by jennpb** [comment]
To get this in a state where we can release, we need to:
- [ ] Put Collections page (with search box and radio buttons) behind toggle `Full catalogue search`
- [ ] Verify 301 redirect is in place `/collections` to `/prismicID`
- [ ] Meet acceptance criteria on #5510

**Comment by jennpb** [comment]
Release notes not yet updated so I'm reopening.
