### ISSUE TITLE
Improving section + content browsing and navigation

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5369]
# What is it and who's it for?

All site users

Due to the long-running iterative development of the site, we've ended up with a lot of variety in our page templates, making it much harder to see a consistent site hierarchy and build out pages that contain a lot of content.

Given that we're now expanding the amount of content on the site (through shutting down [wellcomelibrary.org](http://wellcomelibrary.org) and recreating all of its content based on user needs), we need to take a holistic view of the site to make improvements across the whole design system, as it relates to page templates and content hierarchy.

**This project's aim is to improve the page-by-page, section-by-section browsing experience on the site.**

Project Brief: https://www.notion.so/wellcometrust/Project-Brief-Improving-section-content-browsing-and-navigation-8d11582ef0e14a95a1a617a394f919ea

## Initiatives
- [ ]  Section-level page headers with custom functionality (#5432)
- [x] Harmonizing section, list and content page (with/without featured image) headers (#5411)
- [ ] Headings AA compliance #4607
- [x]  Headings hierarchy #4860
- [x] Anchor links on content pages https://github.com/wellcomecollection/wellcomecollection.org/issues/5561

## Measurement
- Increase on-site page views

## Other considerations 
<---Delete as appropriate--->
- Impact on URL design
- Cardigan documentation

**Comment by jennpb** [comment]
Relates to https://github.com/wellcomecollection/platform/issues/4646

**Comment by pollecuttn** [comment]
21 July 2020:

- [x] List/content pages
- [x] Content pages with hero image
- [ ] Section page with custom functionality, with bigger header and a different treatment in addition to photography

**Comment by jennpb** [comment]
Dealing with this as now-separate issues.
