### ISSUE TITLE
Harmonize page templates across Sections, Lists and Content pages

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5432]
# What is it and who's it for?
All site users

Due to the long-running iterative development of the site, we've ended up with a lot of variety in our page templates, making it much harder to see a consistent site hierarchy.

As we've iterated on a section-by-section basis, we've created some pages with custom functionality, and those pages sometimes also have hero images. We've already done the work on making the cards and card groupings consistent across all sections (pending content development), but the headings of these page templates needs work:
- section-level pages (Visit us, What's on, Stories, Collections, Get involved/What we do)
- landing pages
- list/index pages
- content pages

Project Brief: https://www.notion.so/wellcometrust/Project-Brief-Improving-section-content-browsing-and-navigation-8d11582ef0e14a95a1a617a394f919ea

## Problems to solve
- Lack of consistency in background graphic
- Over-dominant hero image takes up a significant amount of page real estate and is a barrier to any possible custom functionality (a search box; filters; dynamic info). 
- Setting guidelines for each template's header
- Resolving the alignment problem here #6045 

# Implementation 

**Implement according to these Zeplin files**
Section-level pages have **Page title** (increase to 50px - add to typescale), Section summary text (17px)
Sections are: Visit us, What's on, Collections, Stories and Get involved (still in Prismic)

- What's on https://zpl.io/aX66vmp (desktop)
- What's on https://zpl.io/bop3YNm (mobile)
- Collections https://zpl.io/bP66j1k (desktop)
- Collections https://zpl.io/bANNedP (mobile)
- Stories https://zpl.io/2yKKZPw (desktop)
- Stories https://zpl.io/29pml1p (mobile)
- Visit us https://zpl.io/a7jgAGp (desktop)
- Visit us https://zpl.io/V4gRELp (mobile)

**IGNORE CURRENT WHAT WE DO SECTION** - this is being revamped as a proper section-level page with the title of `Get involved` which is currently in development in [Prismic](https://preview.wellcomecollection.org/pages/YDaZmxMAACIAT9u8)

## TODO
- [x] Get summaries for each of the sections from Editorial. (@jennpb asked @dannybirchall and lalita on 24/2)
- [x] Implementing new section-level headers
- [x] Document page templates in Notion @GarethOrmerod 

## Acceptance criteria 
- Design implemented with agreed updates
- Editors can edit the summary for each page in Prismic
- Passes accessibility tests

**Comment by jennpb** [comment]
Relates to KR wellcomecollection/platform#4645

**Comment by GarethOrmerod** [comment]
Designs looking to introduce consistency across Section pages: [App](zpl://project?pid=5aab926b4b6efde01259e959&tags=Page%20header) • [Web](https://zpl.io/bL6vyP7)

**Comment by jennpb** [comment]
# Section summaries

**Visit Us** 

`Wellcome Collection is a free museum and library connecting science, medicine, life and art. Come and see the exhibitions, events and collections in our beautiful building in central London. You will need a ticket to enter the building. `

**What’s on** 

`Come to events and exhibitions, online and in our building. All our permanent and temporary exhibitions are free, and so are most of our events. We hold a wide variety of events throughout the year, from tours to multi-part festivals. `

 **Stories** 

`Our stories relate to health and the human experience. We use words and pictures in a variety of ways to make connections, provoke new thinking and share lived experiences. Dive into a story no matter where in the world you are. `

**Collections** 

`Our collections are at the heart of what we do. Find out what we have by searching online or visiting our library. If you’re interested in exploring and researching our collections, we’re here to support you. `

 
**Get involved** 

`Get involved with what’s happening at Wellcome Collection. From activities for specific groups, such as young people, to opportunities for collaboration and working with us, it’s up to you just how involved you’d like to be. `

**Comment by ishouty** [comment]
@jennpb do you we need all the section summaries to be in prismic for the editorial team to update? stories is static at the moment, collections and whats-on are not primisic pages ?
Thanks

**Comment by dannybirchall** [comment]
It would be v v useful for my team if these were Prismic editable.
