### ISSUE TITLE
Interpretation types in Prismic need to handle title, label and messaging independently

### ISSUE THREAD

**Issue by jennpb** [wellcomecollection/wellcomecollection.org#5791]
# What is it and who's it for?
- Content editors who need to add `interpretationType` to Events

The `interpretationType` in Prismic contains these 4 fields:
- Title
- Abbreviation
- Message
- Message if primary interpretation

The `Title` of an `interpretationType` is used for two purposes:
- Identifying the content item in a Prismic list (see screenshot below)
- Adding the label text to the card's yellow label

<img width="375" alt="Screenshot 2020-11-19 at 16 47 31" src="https://user-images.githubusercontent.com/1446139/99696785-fcc9cd00-2a86-11eb-80da-de7956e3bbf6.png">

**We need a way to split out these functions so that they are independent of each other.**

**Why?**
The Editorial team create a new `interpretationType` to accommodate variant messaging about the event's interpretation. But because the label needs to be consistent in order to appear on the card in the right way, we end up with multiple interpretation types with the same name - making it difficult for the Editors to choose which one goes with their content.

<img width="574" alt="Screenshot 2020-11-19 at 16 30 30" src="https://user-images.githubusercontent.com/1446139/99696337-8200b200-2a86-11eb-9778-bce19ab3d726.png">

The messages attached to each instance are:

**Audio described**
This event will be audio described for visitors who are blind or partially sighted. Places are free but very limited. If you would like to come along, email 

**Audio described (online)**
This event is audio described, which may be useful for people who are blind or partially sighted. For any assistance, please email us at .

**Auto-captioned (online)**
There will be auto-generated captions for this event. For any assistance, please email us at 

**British Sign Language** (1)
This event will have British Sign Language interpretation. If you would like to come along, email us at .

**British Sign Language** (2)
This event will be delivered in British Sign Language, with English voiceover. If you would like to come along, email us at .

**British Sign Language (online)**
This event is British Sign Language interpreted. A signer will be on screen describing the event. For any assistance, please email us at 

**Captioned**
This event will be Captioned and the captions will be visible throughout the performance space. 
**Captioned - online**
The main panel discussion will be captioned by StageText, and the introduction and Q&A will be auto-captioned by Bluejeans, the videoconferencing platform.

**Hearing loop**
There will be an induction loop at this event for visitors with hearing aids. 

**Relaxed performance**
This is a relaxed performance, which means that if you need to, you are welcome to move around and make noise at any time. 

**Speech-to-text**
This event will have live speech-to-text transcription for visitors who are D/deaf or hard of hearing. 

**Speech-to-text (online)**
This event will have live speech-to-text transcription, which may be useful for people who are D/deaf or hard of hearing. 

## Proposed solution

- Allow `title` of `interpretationType` to be anything - in order to help Editors choose it from the list of interpretations
- Add extra `label text` field in the content item so Editors can choose commonly-accepted labels (British Sign Language, Audio Described, etc).

## Tasks
- [ ] Update content to only use 1 interpretation per type. e.g. 1 BSL with multiple descriptions.

**Comment by jamesgorrie** [comment]
Thinking about filters for these, if we have `/events?with=bsl`<sup>*</sup> - would we expect all of the BSL options to be in that list?

<sup>*</sup> pseudo implementation

**Comment by jennpb** [comment]
My preference would be that we have BSL as one option (and either deal with the variant multiples differently)

The list of filters would look like this:

Access:
British Sign Language
Audio described
Auto-captioned
Captioned
Relaxed performance
Speech to Text

**Comment by jamesgorrie** [comment]
@jennpb a few questions here:

> This event will be delivered in British Sign Language, with English voiceover

Should this then be `BSL` and `English voiceover`?


> (Online)

What we could do is just add a field to the `interpretationType` called `onlineDescription` and render that if the event is flagged as `isOnline`.

**Comment by jamesgorrie** [comment]
[This has been handled here](https://github.com/wellcomecollection/wellcomecollection.org/pull/5882).

Things todo:
- [ ] Content team to go in and slim down list to just 1 BSL and other interpretation types
- [ ] Anything to do with filters?

**Comment by jennpb** [comment]
No filters work just now ([see comment](https://github.com/wellcomecollection/wellcomecollection.org/issues/2765#issuecomment-737894643))

**Comment by jamesgorrie** [comment]
We said that we might add different descriptions onto access modes, and a free text box, similar to contributors, to add extra information.

We started with the latter half of that and add flexibility as @dannybirchall  said, we’re still finding our feet. We’ve added an “Extra information” box to the access mode. It the appends this info to the access mode description.

The info box is now always available for people to see whereas it was hidden on past events.

I’ve attached screenshots, but you should be able to go into Prismic and see how it works.

![extrainfo](https://user-images.githubusercontent.com/31692/102203496-9175ee00-3ec0-11eb-8843-0fcfc08b23b2.png)

![extrainfopris](https://user-images.githubusercontent.com/31692/102203499-920e8480-3ec0-11eb-83f1-5f18e5e51564.png)

**Comment by jamesgorrie** [comment]
@jennpb A content task would be to go through and make sure we are using 1 BSL etc I've added it to the description of this issue.
