### ISSUE TITLE
Accessibility research for general usability, content and understanding of Wellcome collection 

### ISSUE THREAD

**Issue by alicerichmond** [wellcomecollection/wellcomecollection.org#5852]
**We want users to be able to**
Access all parts of our website and functionality without impediment, including those using screen readers, magnifiers, pointers, tabbed navigation and voice commands

**but we hypothesise this is happening**
that we are doing ok with our accessibility but we havent had any users test it thoroughly with their specific set ups to indicate to us that there might be an issue with accessing different components

**We are right if we measure**
- Ability to navigate through the archive tree
- Ability to undertake a search and locate an item of interest
- Ability to use the viewer to read, magnify and understand materials including the available volumes
- General comprehension of the written language of the site

**and get this result**
Regardless of the type of accessibility tool used participants are able to undertake and understand the tasks involved in using the Collection site

**The deadline for results is**
End of january

Tasks to undertake

- [ ] Develop a brief for People for research to help them understand our needs 

- [ ] Create research questions 

- [ ] Organise times for interviews

**Comment by alicerichmond** [comment]
Using airtable to plot out the key points of testing and ensuring that we map all of the tasks to these
