### ISSUE TITLE
Conversion tracking

### ISSUE THREAD

**Issue by jamesgorrie** [wellcomecollection/wellcomecollection.org#5939]
**What**
There's a few bugs / additions we need to make the conversion tracking fully useful

- [x] item page tracks twice #5957
- [x] add source to item page link and others to dedupe on things like pagination #5958
- [x] add position to worklink #5958
- [x] sessions #5960
- [ ] outbound links
- [ ] audio/video tracking

**Where**
Across all the search pages

**Comment by taceybadgerbrook** [comment]
@james have outbound links and audio/video tracking been left off for a reason?
