### ISSUE TITLE
Security improvements

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/wellcomecollection.org#7344]
Here is a list of things we might want to do to improve security. Refer to the [OWASP cheat sheets](https://cheatsheetseries.owasp.org/) for details.

- [x] [Strict Transport Security](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) - enforce HTTPS. This should be for the whole site, not the API. It needs to be done carefully with a check for mixed content first. See [this blog post](https://www.troyhunt.com/understanding-http-strict-transport/) for useful details.
  Impact: **High** 🔴 
  Effort: **Medium** 🟠 
- [ ] [Content Security Policy](https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html) (+ [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)) - For prevention of XSS. Should be tested with report-only first. Supersedes `X-XSS-Protection`. 
  Impact: **High** 🔴 
  Effort: **Medium** 🟠 
- [x] Disable all admin-related endpoints, validations and authorisations - these are no longer required.
  Impact: **High** 🔴 
  Effort: **Medium** 🟠 
- [x] Review all user input validation and rendering of user input (ie injection and XSS attacks)
  Impact: **Medium** 🟠 
  Effort: **Medium** 🟠 
- [x] [Other minor security headers](https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#introduction). Eg `X-Frame-Options`, `X-Content-Type-Options`.
  Impact: **Low** 🟢 
  Effort: **Low** 🟢 
- [x] [Explicit SameSite: Lax for session cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) - this is the default in recent browsers but should be explicit
  Impact: **Low** 🟢 
  Effort: **Low** 🟢 
- [x] Make the identity API authorizer deny-by-default - currently the fallthrough case in the authorizer is to allow access. This should be refactored to be deny-by-default.
  Impact: **Low** 🟢 
  Effort: **Low** 🟢

**Comment by jamieparkinson** [comment]
Closing for now as CSP is difficult and we have no evidence that we really require it right now
