### ISSUE TITLE
PEN testing - Requesting/Account

### ISSUE THREAD

**Issue by cbowskill** [wellcomecollection/wellcomecollection.org#7356]
# What is it and who's it for?
As part of the implementation of new account/requesting functionality we need to ensure that it has been implemented in a secure fashion.
D&T will run a PEN test across the functionality, focusing on the account login / access.

https://auth0.com/docs/support/policies/penetration-testing-policy

- [x] Support ticket raised with Auth0 highlighting details and dates of the test (7 days notice required)
- [x] Understand any changes or impact to implementation (will move to a preview tenant)
- [x] PEN test conducted and findings shared (2-3 days)

**Comment by cbowskill** [comment]
Closed, changes identified have been actioned and verified. Happy to proceed to live.
