### ISSUE TITLE
Day picker accessibility

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#7457]
references #7266
Improve accessibility of the day picker
- [x] the input can easily be operated by mouse
- [x] the input can be easily operated on touch devices, e.g.  smartphones, tablets or desktops/laptops with touch screens.
- [x]  the input can be easily operated by keyboard
- [x] users of all input methods should be aware of which dates are unavailable for selection

**Comment by gestchild** [comment]
Fixed in #7612
