### ISSUE TITLE
Turn off requesting for long bank holiday

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8010]
**What**
LE&E have asked for document ordering [requesting] to be turned off at 10:00am on Wednesday 1 June until 09:00am on Monday 6 June.

We have a [toggle ](https://dash.wellcomecollection.org/toggles/) 'Enables login and requesting functionality'. I think we want to turn off requesting functionality only. I don't think there's any need to turn off logging in.

Whilst you need to login to request, you can also login just to see what you already have requested. So there is a case where someone might want to login without also making a request.

LE&E would prefer if we could just switch off requesting and retain being able to login to accounts, but would accept switching off both. They may, in future, want to turn off requesting over the Christmas/NY break but retain being able to login to accounts.

**Questions**
- ~~Are we confident we can use the toggle to switch requesting on and off? We had this issue with the toggle when we first brought requesting out from behind a toggle https://github.com/wellcomecollection/wellcomecollection.org/issues/7778~~
This code isn't behind a toggle currently.

**NB**
Once the requesting date select is deployed, this would prevent requesting during closure periods.

**TODO**
- [x] Consider what messaging there would be and where when we turn off the requesting button e.g. disable button and have messaging in the item note that requesting is switched off during closure
- [x] Put turning off requesting behind a toggle
- [ ] Turn off requesting Wednesday 1 June 10.00am
- [ ] Turn on requesting Monday 6 June 09.00 am
