### ISSUE TITLE
Audio guides: collecting and storing media data

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8107]
# What is it and who's it for?

# User story
As a Wellcome developer
I need to ascertain how we will collect and store media data 

# Implementation 

- confirm how we will store media data
- confirm where we will store media data
- Identify if there are any risks in any of the options
- Identify the most user friendly way in which to upload that data
- Identify the most useful data format for each media type

## Acceptance criteria

- [x] we know how we will store media data
- [x] we know where we will store media data
- [x] we are aware of any risks and what to do about them
- [x] we know the most user friendly way in which to upload that data
- [x] we know the most useful data format for each media type

**Comment by davidpmccormick** [comment]
## Video
YouTube is the obvious choice.

## Audio
SoundCloud has an API that looked promising, but there is no way to adjust playback rate, and this feels like a dealbreaker.

We could treat everything as a video and upload audio to YouTube, but we'd have to display a video playing area to be compliant with YouTube's terms of service, and we'd have to convert audio files to video files. So while we'd get the benefits conferred by YouTube choosing an appropriate quality based on the user's network, we'd necessarily be serving a too-big (video) file in the first place. All in all feels a bit clunky.

Prismic has an upload limit of 100mb for audio. I think this should be sufficient for the content that we want to serve. I'm currently feeling like using our `AudioPlayer` (that uses an html `<audio>` element) with content from Prismic feels like the best option for now.

**Comment by alexwlchan** [comment]
Closing as this is in the Archive column on the [Digital access board](https://github.com/orgs/wellcomecollection/projects/18).
