### ISSUE TITLE
Audio guides: playing videos

### ISSUE THREAD

**Issue by pollecuttn** [wellcomecollection/wellcomecollection.org#8108]
# What is it and who's it for?

# User story
As a wellcome visitor who is D/deaf
I want to play BSL videos on my apple/android phone
so that I can understand what is in the gallery

## Acceptance criteria
- [ ] A visitor can play BSL videos on their phone

## Testing and tracking
- [ ] How many have clicked to play
- [ ] How long did they play for
- Setting up additional tracking and monitoring - talk to Tacey
- Qual and/or Quant test plan - Alice and Tacey

**Comment by alexwlchan** [comment]
Closing as this is in the Archive column on the [Digital access board](https://github.com/orgs/wellcomecollection/projects/18).
