### ISSUE TITLE
Set up digital guides pages in content app

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#8163]
- [x] create skeleton digital guides pages
- [x] add routing for digital guides pages
- [x] add digital-guides to link-resolvers
