### ISSUE TITLE
Works page navigation UX refinement

### ISSUE THREAD

**Issue by DominiqueMarshall** [wellcomecollection/wellcomecollection.org#8907]
As part of improving the works page navigation, the initial design of the tabbed view approach needs to be reviewed to see how it works across other digitised work types, taking into account cases like works with long titles, video and audio-based works, etc.

- [x] Review what the tabs will look like across other digitised work types (especially works with long titles)
- [x] Review how the tabbed nav will work with video and audio content
- [x] Add the search bar back to the initial tabbed view designs
- [x] Assess the microcopy across the journey to see what makes sense and what needs updating

**Comment by DominiqueMarshall** [comment]
Thanks for the feedback @jennpb! 

Bbutton treatment options below. I amended the contents navigation styling to how it is live now, so there's less of a design clash:

- solid button: https://zpl.io/5EM4lX8
- outline button: https://zpl.io/p1Q3qpJ
- text link: https://zpl.io/jZe3KAx

I've moved the search bar back to the sidebar in the above mockups. However, here's an example of what the 'search within' results pattern could look like if we kept it within the top bar: https://zpl.io/jZe3L8O, and what it could look like if the icons were given labels: https://zpl.io/EmzQkRY _(the text is quite small in this though, so I'm not convinced it would be a good approach)_.

I've also tidied up the downloads modal here (removed the credit info that's repeated in the side panel: https://zpl.io/NwdxkDk

**Comment by DominiqueMarshall** [comment]
cc @davidpmccormick @gestchild 

Final designs as discussed in our catch-up:

Item viewer variant design: https://zpl.io/09nrvNl
Download modal change: https://zpl.io/3X7r4Py

Mobile side panel: https://zpl.io/1ym3E4m, https://zpl.io/6NOAnwP

**Comment by jennpb** [comment]
@gestchild @DominiqueMarshall 

Download modal change: At the moment, there is inconsistency of formatting between the licence and credit information in the modal and in the side panel, and a bit of jank.

![Image](https://user-images.githubusercontent.com/1446139/210348096-dd3831ec-0884-46bf-a567-91ce527b5c4e.png)


- The modal has the human readable licence text; the panel does not.
- The modal's credit line includes both the source link and the licence link - this is the preferable option because it's easier for a user to copy-paste it if needed; the panel breaks out the Source link into a new line, and does not include the licence link.
- On mobile, the modal doesn't scroll

![Image](https://user-images.githubusercontent.com/1446139/210348353-e0982e16-5116-4d37-8857-38547226b3a2.png)


## Proposed actions

- We go ahead and remove the licence + credit information from the modal as shown in the Zeplin link. This means we don't need to fix the non-scrolling in modal issue.
- We revisit the formatting and display of the licence + credit information across work page + digitised item viewer, as part of further work to rationalise the information hierarchy and utility of the works pages.
