### ISSUE TITLE
New Search release

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9034]
Thought I'd write something down so we're all align for the release of the new search, which could be considered once these tickets are done:

- [x] [Search overview BE](https://github.com/wellcomecollection/wellcomecollection.org/issues/8805) 
- [x] [Search overview FE](https://github.com/wellcomecollection/wellcomecollection.org/issues/8741)
- [x] [Theming filters](https://github.com/wellcomecollection/wellcomecollection.org/issues/8935) 
- [x] [Rethink default states](https://github.com/wellcomecollection/wellcomecollection.org/issues/9041)
- [x] [Exclude some articles from the results](https://github.com/wellcomecollection/wellcomecollection.org/issues/9003)
- [x] [Update search metadata](https://github.com/wellcomecollection/wellcomecollection.org/issues/8934)
- [x] [Update data sent to analytics](https://github.com/wellcomecollection/wellcomecollection.org/issues/8977) (maybe? Harrison to confirm)
- [x] [Dom to review design](https://github.com/wellcomecollection/wellcomecollection.org/issues/9049)
- [x] Fix various bugs (prefixed with "Search:" in the board) as they are raised, if we consider them blockers for the release. (ongoing, but all blockers have been fixed and deployed)

CURRENTLY HERE 🟢  And we're happy with what's behind the toggle, then we could apply these steps in this order:

- [x] Set New Search toggle to true by default
- [x] [Add new search pages to Pa11y](https://github.com/wellcomecollection/wellcomecollection.org/issues/9053)
- [x] [Fix Pa11y bugs](https://github.com/wellcomecollection/wellcomecollection.org/issues/9180)
- [x] [Add tests for new search](https://github.com/wellcomecollection/wellcomecollection.org/issues/9193)
- [x] Confirm we have what we need for analytics ([Ticket for @taceybadgerbrook](https://github.com/wellcomecollection/wellcomecollection.org/issues/9238))
- [x] Fix various bugs and UI changes as they are raised, if we consider them blockers for the release.

Then: 
- [x] [Deploy Redirects to new search](https://github.com/wellcomecollection/wellcomecollection.org/issues/8713)
- [x] [Add Searchbar to header](https://github.com/wellcomecollection/wellcomecollection.org/issues/8736) (Behind a toggle to start)

Once we're 100% happy with it, we should

- [x] Ensure Search bar in Works links to new page
- [x] [Update Search bar on Collections](https://github.com/wellcomecollection/wellcomecollection.org/issues/8708)
- [x] Delete `/works` and `/images` from the codebase ([PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/9371))
- [x] Check if we can delete SearchTabs (or refactor them) see #9351 (cleaned up a little bit already in [this PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/9372))
- [x] Check if we can delete the old Sort component (only use was in `/works`) ([PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/9372))
- [x] Remove them from pa11y ([PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/9371)) 
- [x] Remove all tests related to it.
- [x] Remove new search toggle completely (keep events & exhibitions toggle)
- [x] Remove global header toggle completely ([PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/9370))
- [x] Aim to clean up as many `isNewStyle` related CSS as possible and align components across the website. Also rename anything that might refer to "new search". ([PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/9389))
- [x] [Cleanup the isFilter workaround in the old filters, we don't need that parameter anymore](https://github.com/wellcomecollection/wellcomecollection.org/blob/9623962a852f39820b0610dba4ba0ce02c875932/common/views/components/DropdownButton/DropdownButton.tsx#L98) ([PR](https://github.com/wellcomecollection/wellcomecollection.org/pull/9387))
- [x] Cleanup references to `/works` and `/images` on third party platforms ? (CloudFront for example?)

This of course is a suggestion to start the conversation, please do suggest, comment or correct anything :)

**Comment by rcantin-w** [comment]
Removed [Remove search bar from works](https://github.com/wellcomecollection/wellcomecollection.org/issues/8735) from the list. We won't be doing that at least until the search is in the header, therefore still accessible to users. See conversation in ticket.

**Comment by rcantin-w** [comment]
I'd like to suggest a quick review from @DominiqueMarshall before the release, if we can. @AMBacelar and I just talked about a button's colour that seemed not to fit, and wondered if there'd be other things that would be good to tweak before we went ahead!

**Comment by rcantin-w** [comment]
https://github.com/wellcomecollection/wellcomecollection.org/issues/9041 is being added as necessary before release.

**Comment by DominiqueMarshall** [comment]
@rcantin-w can you let me know specifically what you'd like me to review, please? 😊

**Comment by rcantin-w** [comment]
@DominiqueMarshall we could go through all the new pages and see if anything needs tweaking. I could book a call once we feel close to the end of the integration and run through it together? I'm thinking it'll mostly be spacing related and confirming a few colour choices.

**Comment by rcantin-w** [comment]
Linking the feedback document here so it's documented: https://docs.google.com/document/d/1UHaHXMRSioQNesUMYUHdjlHRtAipDva_caCplhGpOxI/edit#

**Comment by rcantin-w** [comment]
Ticking "Dom reviewing design" as it'll be an ongoing process but she's confirmed there are no blockers currently for a release.

**Comment by rcantin-w** [comment]
Everything being ticked, considering this piece of work done :)
