### ISSUE TITLE
Cardigan: Update to Storybook 8

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/wellcomecollection.org#9158]
**EDIT:** (23/10/23)
We'll move to Storybook 7, which uses Vite by default. 
There are a few other tickets to consider as part of this work

- [x] [Review possibly unused components](https://github.com/wellcomecollection/wellcomecollection.org/issues/10272)
- [ ] [Cardigan: Add missing components / fix others](https://github.com/wellcomecollection/wellcomecollection.org/issues/9157)
- [ ] [Group mock content (Cardigan, tests)](https://github.com/wellcomecollection/wellcomecollection.org/issues/10289) could also be useful if done before?
- [ ] Consider [this TODO]: remove Table? (https://github.com/wellcomecollection/wellcomecollection.org/blob/34ef71501f1ec8683185b4802351e9074a0e58bb/content/webapp/components/Table/Table.tsx#L3)
- [x] Remove the relevant packages from [Dependabot's ignore list](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/.github/dependabot.yml) once upgraded.

----

Work had been attempted by @davidpmccormick  in an older PR: https://github.com/wellcomecollection/wellcomecollection.org/pull/8711

We've decided to split it in multiple tickets. This is to take up the work again and ensure we're using latest versions (and hopefully faster ones 🤞 )

https://storybook.js.org/blog/storybook-for-vite/

**Comment by davidpmccormick** [comment]
Storybook 7 findings so far:

- CSF files need
	1. a `default export` that describes the overall component
	2. named `exports` for individual stories
	3. no explicit render function if `component` is defined in the (default exported) meta
- `.mdx` files shouldn’t be `.stories.mdx` and index needs to be updated accordingly
- if `Meta` needs a title, it has to be a string literal (not `{JSX}`)
- imported `.md` files (e.g. component READMEs) should be included via the `Markdown` export of `@storybook/blocks`
- add a `title` in form e.g. `Components/BackToResults` to the default (meta) output of the CSF file to create sidebar hierarchy (and disabling ‘roots’ seems nicer?)
- use the `Primary` and `Controls` exports from `@storybook/blocks` to render the _first_ export from the CSF, and any arguments, respectively. `Controls` can also take an `of` prop to point to a specific story
- Handle `Context`s with decorators
- I've had no luck getting Vite off the ground so far, but will look at this next

**Comment by rcantin-w** [comment]
... Storybook 8? https://storybook.js.org/releases/8.0

**Comment by rcantin-w** [comment]
> [!NOTE]
> **Please remember to remove the relevant packages from [Dependabot's ignore list](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/.github/dependabot.yml) once upgraded.**

**Comment by davidpmccormick** [comment]
Closing since Storybook has been upgraded and the remaining unchecked todos have related issues.
