### ISSUE TITLE
Set up tracking in GTM for 'catalogue details' link from /items to /works

### ISSUE THREAD

**Issue by gestchild** [wellcomecollection/wellcomecollection.org#9664]
Relates to #9471

- [ ] add data attribute to link to act as hook for GTM event
- [ ] set up tracking in GTM
- [ ] add event to [table in gitbook ](https://app.gitbook.com/o/-LumfFcEMKx4gYXKAZTQ/s/MM8zK9GZyFCpy8kvd5Km/analytics-and-reporting/google-analytics/analytics-event-tracking)

**Comment by gestchild** [comment]
After discussion, we've decided it best to keep the current Segment tracking in place and that this doesn't require additional tracking in GTM
